/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-Containers"
 * 	found in "LCS-AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_ProtocolExtensionContainer.h"

#include "LCS_AP_ProtocolExtensionField.h"
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P4_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P5_constr_11 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P6_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P7_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P8_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P9_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P10_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P11_constr_23 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P12_constr_25 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P13_constr_27 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P14_constr_29 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P15_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P16_constr_33 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P17_constr_35 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P18_constr_37 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P19_constr_39 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P20_constr_41 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P21_constr_43 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P22_constr_45 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P23_constr_47 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P24_constr_49 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P25_constr_51 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P26_constr_53 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P27_constr_55 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P28_constr_57 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P29_constr_59 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_E_CGI_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P0_specs_1 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P0),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0_tags_1,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0_tags_1)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0_tags_1)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P0_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P0_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P0_1,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P1_specs_3 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P1),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1_tags_3,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1_tags_3)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1_tags_3[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1_tags_3)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P1_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P1_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P1_3,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P2_specs_5 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P2),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2_tags_5,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2_tags_5)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2_tags_5[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2_tags_5)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P2_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P2_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P2_5,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P3_specs_7 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P3),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3_tags_7,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3_tags_7)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3_tags_7[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3_tags_7)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P3_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P3_constr_7,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P3_7,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P3_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P4_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ellipsoid_Arc_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P4_specs_9 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P4),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4_tags_9,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4_tags_9)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4_tags_9[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4_tags_9,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4_tags_9)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P4_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P4_constr_9,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P4_9,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P4_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P5_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Geographical_Coordinates_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P5_specs_11 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P5),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5_tags_11,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5_tags_11)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5_tags_11[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5_tags_11,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5_tags_11)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P5_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P5_constr_11,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P5_11,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P5_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P6_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P6_specs_13 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P6),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6_tags_13,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6_tags_13)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6_tags_13[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6_tags_13,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6_tags_13)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P6_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P6_constr_13,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P6_13,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P6_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P7_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P7_specs_15 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P7),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7_tags_15,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7_tags_15)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7_tags_15[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7_tags_15,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7_tags_15)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P7_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P7_constr_15,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P7_15,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P7_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P8_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P8_specs_17 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P8),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8_tags_17,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8_tags_17)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8_tags_17[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8_tags_17,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8_tags_17)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P8_constr_17,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P8_17,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P8_specs_17	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P9_19[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P9_specs_19 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P9),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P9, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9_tags_19,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9_tags_19)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9_tags_19[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9_tags_19,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9_tags_19)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P9_tags_19[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P9_constr_19,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P9_19,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P9_specs_19	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P10_21[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P10_specs_21 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P10),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P10, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10_tags_21,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10_tags_21)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10_tags_21[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10_tags_21,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10_tags_21)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P10_tags_21[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P10_constr_21,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P10_21,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P10_specs_21	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P11_23[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P11_specs_23 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P11),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11_tags_23,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11_tags_23)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11_tags_23[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11_tags_23,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11_tags_23)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P11_tags_23[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P11_constr_23,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P11_23,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P11_specs_23	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P12_25[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P12_specs_25 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P12),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P12, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12_tags_25,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12_tags_25)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12_tags_25[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12_tags_25,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12_tags_25)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12_tags_25[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P12_constr_25,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P12_25,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P12_specs_25	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P13_27[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Horizontal_Velocity_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P13_specs_27 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P13),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P13, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13_tags_27,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13_tags_27)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13_tags_27[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13_tags_27,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13_tags_27)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P13_tags_27[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P13_constr_27,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P13_27,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P13_specs_27	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P14_29[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P14_specs_29 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P14),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P14, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14_tags_29,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14_tags_29)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14_tags_29[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14_tags_29,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14_tags_29)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14_tags_29[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P14_constr_29,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P14_29,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P14_specs_29	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P15_31[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P15_specs_31 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P15),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15_tags_31,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15_tags_31)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15_tags_31[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15_tags_31,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15_tags_31)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P15_tags_31[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P15_constr_31,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P15_31,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P15_specs_31	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P16_33[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P16_specs_33 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P16),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16_tags_33,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16_tags_33)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16_tags_33[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16_tags_33,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16_tags_33)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P16_tags_33[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P16_constr_33,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P16_33,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P16_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P17_35[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Point_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P17_specs_35 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P17),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P17, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17_tags_35,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17_tags_35)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17_tags_35[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17_tags_35,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17_tags_35)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P17_tags_35[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P17_constr_35,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P17_35,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P17_specs_35	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P18_37[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Point_With_Uncertainty_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P18_specs_37 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P18),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P18, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18_tags_37,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18_tags_37)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18_tags_37[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18_tags_37,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18_tags_37)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P18_tags_37[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P18_constr_37,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P18_37,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P18_specs_37	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P19_39[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Polygon_Point_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P19_specs_39 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P19),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P19, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19_tags_39,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19_tags_39)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19_tags_39[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19_tags_39,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19_tags_39)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P19_tags_39[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P19_constr_39,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P19_39,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P19_specs_39	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P20_41[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Positioning_Data_ExtIEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20_tags_41[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P20_specs_41 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P20),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P20, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20_tags_41,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20_tags_41)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20_tags_41[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20_tags_41,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20_tags_41)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20_tags_41[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P20_constr_41,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P20_41,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P20_specs_41	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P21_43[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Request_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21_tags_43[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P21_specs_43 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P21),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P21, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21_tags_43,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21_tags_43)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21_tags_43[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21_tags_43,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21_tags_43)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P21_tags_43[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P21_constr_43,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P21_43,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P21_specs_43	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P22_45[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Response_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22_tags_45[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P22_specs_45 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P22),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P22, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22_tags_45,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22_tags_45)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22_tags_45[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22_tags_45,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22_tags_45)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P22_tags_45[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P22_constr_45,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P22_45,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P22_specs_45	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P23_47[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Abort_Request_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23_tags_47[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P23_specs_47 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P23),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P23, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23_tags_47,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23_tags_47)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23_tags_47[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23_tags_47,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23_tags_47)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P23_tags_47[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P23_constr_47,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P23_47,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P23_specs_47	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P24_49[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Connection_Oriented_Information_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24_tags_49[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P24_specs_49 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P24),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P24, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24_tags_49,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24_tags_49)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24_tags_49[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24_tags_49,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24_tags_49)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P24_tags_49[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P24_constr_49,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P24_49,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P24_specs_49	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P25_51[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Connectionless_Information_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25_tags_51[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P25_specs_51 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P25),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P25, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25_tags_51,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25_tags_51)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25_tags_51[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25_tags_51,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25_tags_51)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P25_tags_51[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P25_constr_51,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P25_51,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P25_specs_51	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P26_53[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Reset_Request_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26_tags_53[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P26_specs_53 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P26),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P26, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26_tags_53,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26_tags_53)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26_tags_53[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26_tags_53,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26_tags_53)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P26_tags_53[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P26_constr_53,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P26_53,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P26_specs_53	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P27_55[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Reset_Acknowledge_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27_tags_55[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P27_specs_55 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P27),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P27, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27_tags_55,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27_tags_55)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27_tags_55[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27_tags_55,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27_tags_55)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P27_tags_55[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P27_constr_55,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P27_55,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P27_specs_55	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P28_57[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ciphering_Key_Data_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28_tags_57[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P28_specs_57 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P28),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P28, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28_tags_57,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28_tags_57)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28_tags_57[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28_tags_57,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28_tags_57)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P28_tags_57[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P28_constr_57,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P28_57,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P28_specs_57	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolExtensionContainer_108P29_59[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ciphering_Key_Data_Result_Extensions,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29_tags_59[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolExtensionContainer_108P29_specs_59 = {
	sizeof(struct LCS_AP_ProtocolExtensionContainer_108P29),
	offsetof(struct LCS_AP_ProtocolExtensionContainer_108P29, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29_tags_59,
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29_tags_59)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29_tags_59[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29_tags_59,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29_tags_59)
		/sizeof(asn_DEF_LCS_AP_ProtocolExtensionContainer_108P29_tags_59[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolExtensionContainer_108P29_constr_59,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolExtensionContainer_108P29_59,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolExtensionContainer_108P29_specs_59	/* Additional specs */
};

