/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_H_
#define	_LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_High-Accuracy-Uncertainty-Code.h"
#include "LCS_AP_High-Accuracy-Extended-Uncertainty-Code.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_PR {
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_PR_NOTHING,	/* No components present */
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_PR_high_Accuracy_Uncertainty_Altitude,
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_PR_high_Accuracy_Extended_Uncertainty_Altitude
} LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_PR;

/* LCS_AP_High-Accuracy-Scalable-Uncertainty-Altitude */
typedef struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude {
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_PR present;
	union LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_u {
		LCS_AP_High_Accuracy_Uncertainty_Code_t	 high_Accuracy_Uncertainty_Altitude;
		LCS_AP_High_Accuracy_Extended_Uncertainty_Code_t	 high_Accuracy_Extended_Uncertainty_Altitude;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude;
extern asn_CHOICE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_1[2];
extern asn_per_constraints_t asn_PER_type_LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_High_Accuracy_Scalable_Uncertainty_Altitude_H_ */
#include <asn_internal.h>
