/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Misc_Cause_H_
#define	_LCS_AP_Misc_Cause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_Misc_Cause {
	LCS_AP_Misc_Cause_processing_Overload	= 0,
	LCS_AP_Misc_Cause_hardware_Failure	= 1,
	LCS_AP_Misc_Cause_o_And_M_Intervention	= 2,
	LCS_AP_Misc_Cause_unspecified	= 3,
	/*
	 * Enumeration is extensible
	 */
	LCS_AP_Misc_Cause_ciphering_key_data_lost	= 4
} e_LCS_AP_Misc_Cause;

/* LCS_AP_Misc-Cause */
typedef long	 LCS_AP_Misc_Cause_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LCS_AP_Misc_Cause_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Misc_Cause;
extern const asn_INTEGER_specifics_t asn_SPC_LCS_AP_Misc_Cause_specs_1;
asn_struct_free_f LCS_AP_Misc_Cause_free;
asn_struct_print_f LCS_AP_Misc_Cause_print;
asn_constr_check_f LCS_AP_Misc_Cause_constraint;
per_type_decoder_f LCS_AP_Misc_Cause_decode_aper;
per_type_encoder_f LCS_AP_Misc_Cause_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Misc_Cause_H_ */
#include <asn_internal.h>
