/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Uncertainty_Ellipse_H_
#define	_LCS_AP_Uncertainty_Ellipse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Uncertainty-Code.h"
#include "LCS_AP_Orientation-Major-Axis.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCS_AP_Uncertainty-Ellipse */
typedef struct LCS_AP_Uncertainty_Ellipse {
	LCS_AP_Uncertainty_Code_t	 uncertainty_SemiMajor;
	LCS_AP_Uncertainty_Code_t	 uncertainty_SemiMinor;
	LCS_AP_Orientation_Major_Axis_t	 orientation_Major_Axis;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Uncertainty_Ellipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Uncertainty_Ellipse;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Uncertainty_Ellipse_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Uncertainty_Ellipse_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Uncertainty_Ellipse_H_ */
#include <asn_internal.h>
