/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-Containers"
 * 	found in "LCS-AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_ProtocolIE_Field_H_
#define	_LCS_AP_ProtocolIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_ProtocolIE-ID.h"
#include "LCS_AP_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "LCS_AP_Correlation-ID.h"
#include "LCS_AP_Presence.h"
#include "LCS_AP_Location-Type.h"
#include "LCS_AP_E-CGI.h"
#include "LCS_AP_LCS-Client-Type.h"
#include "LCS_AP_LCS-Priority.h"
#include "LCS_AP_LCS-QoS.h"
#include "LCS_AP_UE-Positioning-Capability.h"
#include "LCS_AP_Include-Velocity.h"
#include "LCS_AP_IMSI.h"
#include "LCS_AP_IMEI.h"
#include "LCS_AP_MultipleAPDUs.h"
#include "LCS_AP_RAT-Type.h"
#include "LCS_AP_Coverage-Level.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "LCS_AP_Geographical-Area.h"
#include "LCS_AP_Positioning-Data.h"
#include "LCS_AP_Velocity-Estimate.h"
#include "LCS_AP_Accuracy-Fulfillment-Indicator.h"
#include "LCS_AP_LCS-Cause.h"
#include "LCS_AP_Payload-Type.h"
#include "LCS_AP_APDU.h"
#include "LCS_AP_Network-Element.h"
#include "LCS_AP_Return-Error-Type.h"
#include "LCS_AP_Return-Error-Cause.h"
#include "LCS_AP_Ciphering-Data.h"
#include "LCS_AP_Ciphering-Data-Ack.h"
#include "LCS_AP_Ciphering-Data-Error-Report.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_Location_Request_IEs__value_PR {
	LCS_AP_Location_Request_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Location_Request_IEs__value_PR_Correlation_ID,
	LCS_AP_Location_Request_IEs__value_PR_Location_Type,
	LCS_AP_Location_Request_IEs__value_PR_E_CGI,
	LCS_AP_Location_Request_IEs__value_PR_LCS_Client_Type,
	LCS_AP_Location_Request_IEs__value_PR_LCS_Priority,
	LCS_AP_Location_Request_IEs__value_PR_LCS_QoS,
	LCS_AP_Location_Request_IEs__value_PR_UE_Positioning_Capability,
	LCS_AP_Location_Request_IEs__value_PR_Include_Velocity,
	LCS_AP_Location_Request_IEs__value_PR_IMSI,
	LCS_AP_Location_Request_IEs__value_PR_IMEI,
	LCS_AP_Location_Request_IEs__value_PR_MultipleAPDUs,
	LCS_AP_Location_Request_IEs__value_PR_RAT_Type,
	LCS_AP_Location_Request_IEs__value_PR_Coverage_Level
} LCS_AP_Location_Request_IEs__value_PR;
typedef enum LCS_AP_Location_Response_IEs__value_PR {
	LCS_AP_Location_Response_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Location_Response_IEs__value_PR_Correlation_ID,
	LCS_AP_Location_Response_IEs__value_PR_Geographical_Area,
	LCS_AP_Location_Response_IEs__value_PR_Positioning_Data,
	LCS_AP_Location_Response_IEs__value_PR_Velocity_Estimate,
	LCS_AP_Location_Response_IEs__value_PR_Accuracy_Fulfillment_Indicator,
	LCS_AP_Location_Response_IEs__value_PR_LCS_Cause
} LCS_AP_Location_Response_IEs__value_PR;
typedef enum LCS_AP_Location_Abort_Request_IEs__value_PR {
	LCS_AP_Location_Abort_Request_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Location_Abort_Request_IEs__value_PR_Correlation_ID,
	LCS_AP_Location_Abort_Request_IEs__value_PR_LCS_Cause
} LCS_AP_Location_Abort_Request_IEs__value_PR;
typedef enum LCS_AP_Connection_Oriented_Information_IEs__value_PR {
	LCS_AP_Connection_Oriented_Information_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Connection_Oriented_Information_IEs__value_PR_Correlation_ID,
	LCS_AP_Connection_Oriented_Information_IEs__value_PR_Payload_Type,
	LCS_AP_Connection_Oriented_Information_IEs__value_PR_APDU
} LCS_AP_Connection_Oriented_Information_IEs__value_PR;
typedef enum LCS_AP_Connectionless_Information_IEs__value_PR {
	LCS_AP_Connectionless_Information_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Connectionless_Information_IEs__value_PR_Network_Element,
	LCS_AP_Connectionless_Information_IEs__value_PR_Network_Element_1,
	LCS_AP_Connectionless_Information_IEs__value_PR_APDU,
	LCS_AP_Connectionless_Information_IEs__value_PR_Return_Error_Type,
	LCS_AP_Connectionless_Information_IEs__value_PR_Return_Error_Cause
} LCS_AP_Connectionless_Information_IEs__value_PR;
typedef enum LCS_AP_Reset_Request_IEs__value_PR {
	LCS_AP_Reset_Request_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Reset_Request_IEs__value_PR_LCS_Cause
} LCS_AP_Reset_Request_IEs__value_PR;
typedef enum LCS_AP_Reset_Acknowledge_IEs__value_PR {
	LCS_AP_Reset_Acknowledge_IEs__value_PR_NOTHING	/* No components present */
	
} LCS_AP_Reset_Acknowledge_IEs__value_PR;
typedef enum LCS_AP_Ciphering_Key_Data_IEs__value_PR {
	LCS_AP_Ciphering_Key_Data_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Ciphering_Key_Data_IEs__value_PR_Ciphering_Data
} LCS_AP_Ciphering_Key_Data_IEs__value_PR;
typedef enum LCS_AP_Ciphering_Key_Data_Result_IEs__value_PR {
	LCS_AP_Ciphering_Key_Data_Result_IEs__value_PR_NOTHING,	/* No components present */
	LCS_AP_Ciphering_Key_Data_Result_IEs__value_PR_Ciphering_Data_Ack,
	LCS_AP_Ciphering_Key_Data_Result_IEs__value_PR_Ciphering_Data_Error_Report
} LCS_AP_Ciphering_Key_Data_Result_IEs__value_PR;

/* LCS_AP_ProtocolIE-Field */
typedef struct LCS_AP_Location_Request_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Location_Request_IEs__value {
		LCS_AP_Location_Request_IEs__value_PR present;
		union LCS_AP_Location_Request_IEs__LCS_AP_value_u {
			LCS_AP_Correlation_ID_t	 Correlation_ID;
			LCS_AP_Location_Type_t	 Location_Type;
			LCS_AP_E_CGI_t	 E_CGI;
			LCS_AP_LCS_Client_Type_t	 LCS_Client_Type;
			LCS_AP_LCS_Priority_t	 LCS_Priority;
			LCS_AP_LCS_QoS_t	 LCS_QoS;
			LCS_AP_UE_Positioning_Capability_t	 UE_Positioning_Capability;
			LCS_AP_Include_Velocity_t	 Include_Velocity;
			LCS_AP_IMSI_t	 IMSI;
			LCS_AP_IMEI_t	 IMEI;
			LCS_AP_MultipleAPDUs_t	 MultipleAPDUs;
			LCS_AP_RAT_Type_t	 RAT_Type;
			LCS_AP_Coverage_Level_t	 Coverage_Level;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Location_Request_IEs_t;
typedef struct LCS_AP_Location_Response_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Location_Response_IEs__value {
		LCS_AP_Location_Response_IEs__value_PR present;
		union LCS_AP_Location_Response_IEs__LCS_AP_value_u {
			LCS_AP_Correlation_ID_t	 Correlation_ID;
			LCS_AP_Geographical_Area_t	 Geographical_Area;
			LCS_AP_Positioning_Data_t	 Positioning_Data;
			LCS_AP_Velocity_Estimate_t	 Velocity_Estimate;
			LCS_AP_Accuracy_Fulfillment_Indicator_t	 Accuracy_Fulfillment_Indicator;
			LCS_AP_LCS_Cause_t	 LCS_Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Location_Response_IEs_t;
typedef struct LCS_AP_Location_Abort_Request_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Location_Abort_Request_IEs__value {
		LCS_AP_Location_Abort_Request_IEs__value_PR present;
		union LCS_AP_Location_Abort_Request_IEs__LCS_AP_value_u {
			LCS_AP_Correlation_ID_t	 Correlation_ID;
			LCS_AP_LCS_Cause_t	 LCS_Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Location_Abort_Request_IEs_t;
typedef struct LCS_AP_Connection_Oriented_Information_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Connection_Oriented_Information_IEs__value {
		LCS_AP_Connection_Oriented_Information_IEs__value_PR present;
		union LCS_AP_Connection_Oriented_Information_IEs__LCS_AP_value_u {
			LCS_AP_Correlation_ID_t	 Correlation_ID;
			LCS_AP_Payload_Type_t	 Payload_Type;
			LCS_AP_APDU_t	 APDU;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Connection_Oriented_Information_IEs_t;
typedef struct LCS_AP_Connectionless_Information_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Connectionless_Information_IEs__value {
		LCS_AP_Connectionless_Information_IEs__value_PR present;
		union LCS_AP_Connectionless_Information_IEs__LCS_AP_value_u {
			LCS_AP_Network_Element_t	 Network_Element;
			LCS_AP_Network_Element_t	 Network_Element_1;
			LCS_AP_APDU_t	 APDU;
			LCS_AP_Return_Error_Type_t	 Return_Error_Type;
			LCS_AP_Return_Error_Cause_t	 Return_Error_Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Connectionless_Information_IEs_t;
typedef struct LCS_AP_Reset_Request_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Reset_Request_IEs__value {
		LCS_AP_Reset_Request_IEs__value_PR present;
		union LCS_AP_Reset_Request_IEs__LCS_AP_value_u {
			LCS_AP_LCS_Cause_t	 LCS_Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Reset_Request_IEs_t;
typedef struct LCS_AP_Reset_Acknowledge_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Reset_Acknowledge_IEs__value {
		LCS_AP_Reset_Acknowledge_IEs__value_PR present;
		union LCS_AP_Reset_Acknowledge_IEs__LCS_AP_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Reset_Acknowledge_IEs_t;
typedef struct LCS_AP_Ciphering_Key_Data_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ciphering_Key_Data_IEs__value {
		LCS_AP_Ciphering_Key_Data_IEs__value_PR present;
		union LCS_AP_Ciphering_Key_Data_IEs__LCS_AP_value_u {
			LCS_AP_Ciphering_Data_t	 Ciphering_Data;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ciphering_Key_Data_IEs_t;
typedef struct LCS_AP_Ciphering_Key_Data_Result_IEs {
	LCS_AP_ProtocolIE_ID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ciphering_Key_Data_Result_IEs__value {
		LCS_AP_Ciphering_Key_Data_Result_IEs__value_PR present;
		union LCS_AP_Ciphering_Key_Data_Result_IEs__LCS_AP_value_u {
			LCS_AP_Ciphering_Data_Ack_t	 Ciphering_Data_Ack;
			LCS_AP_Ciphering_Data_Error_Report_t	 Ciphering_Data_Error_Report;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ciphering_Key_Data_Result_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Location_Request_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Location_Request_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Location_Request_IEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Location_Response_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Location_Response_IEs_specs_5;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Location_Response_IEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Location_Abort_Request_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Location_Abort_Request_IEs_specs_9;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Location_Abort_Request_IEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Connection_Oriented_Information_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Connection_Oriented_Information_IEs_specs_13;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Connection_Oriented_Information_IEs_13[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Connectionless_Information_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Connectionless_Information_IEs_specs_17;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Connectionless_Information_IEs_17[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Reset_Request_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Reset_Request_IEs_specs_21;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Reset_Request_IEs_21[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Reset_Acknowledge_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Reset_Acknowledge_IEs_specs_25;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Reset_Acknowledge_IEs_25[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ciphering_Key_Data_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ciphering_Key_Data_IEs_specs_29;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ciphering_Key_Data_IEs_29[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ciphering_Key_Data_Result_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ciphering_Key_Data_Result_IEs_specs_33;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ciphering_Key_Data_Result_IEs_33[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_ProtocolIE_Field_H_ */
#include <asn_internal.h>
