/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_Positioning-Data.h"

#include "LCS_AP_Positioning-Data-Set.h"
#include "LCS_AP_GNSS-Positioning-Data-Set.h"
#include "LCS_AP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_LCS_AP_Positioning_Data_1[] = {
	{ ATF_POINTER, 3, offsetof(struct LCS_AP_Positioning_Data, positioning_Data_Set),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Positioning_Data_Set,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"positioning-Data-Set"
		},
	{ ATF_POINTER, 2, offsetof(struct LCS_AP_Positioning_Data, gNSS_Positioning_Data_Set),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_GNSS_Positioning_Data_Set,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"gNSS-Positioning-Data-Set"
		},
	{ ATF_POINTER, 1, offsetof(struct LCS_AP_Positioning_Data, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_ProtocolExtensionContainer_108P20,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_LCS_AP_Positioning_Data_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_LCS_AP_Positioning_Data_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_Positioning_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* positioning-Data-Set */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gNSS-Positioning-Data-Set */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Positioning_Data_specs_1 = {
	sizeof(struct LCS_AP_Positioning_Data),
	offsetof(struct LCS_AP_Positioning_Data, _asn_ctx),
	asn_MAP_LCS_AP_Positioning_Data_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LCS_AP_Positioning_Data_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_Positioning_Data = {
	"Positioning-Data",
	"Positioning-Data",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_Positioning_Data_tags_1,
	sizeof(asn_DEF_LCS_AP_Positioning_Data_tags_1)
		/sizeof(asn_DEF_LCS_AP_Positioning_Data_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_Positioning_Data_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_Positioning_Data_tags_1)
		/sizeof(asn_DEF_LCS_AP_Positioning_Data_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_Positioning_Data_1,
	3,	/* Elements count */
	&asn_SPC_LCS_AP_Positioning_Data_specs_1	/* Additional specs */
};

