/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_Altitude-And-Direction.h"

asn_TYPE_member_t asn_MBR_LCS_AP_Altitude_And_Direction_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_Altitude_And_Direction, direction_Of_Altitude),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Direction_Of_Altitude,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"direction-Of-Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_Altitude_And_Direction, altitude),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Altitude,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"altitude"
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_Altitude_And_Direction_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_Altitude_And_Direction_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* direction-Of-Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* altitude */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Altitude_And_Direction_specs_1 = {
	sizeof(struct LCS_AP_Altitude_And_Direction),
	offsetof(struct LCS_AP_Altitude_And_Direction, _asn_ctx),
	asn_MAP_LCS_AP_Altitude_And_Direction_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_Altitude_And_Direction = {
	"Altitude-And-Direction",
	"Altitude-And-Direction",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_Altitude_And_Direction_tags_1,
	sizeof(asn_DEF_LCS_AP_Altitude_And_Direction_tags_1)
		/sizeof(asn_DEF_LCS_AP_Altitude_And_Direction_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_Altitude_And_Direction_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_Altitude_And_Direction_tags_1)
		/sizeof(asn_DEF_LCS_AP_Altitude_And_Direction_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_Altitude_And_Direction_1,
	2,	/* Elements count */
	&asn_SPC_LCS_AP_Altitude_And_Direction_specs_1	/* Additional specs */
};

