/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_Horizontal-With-Vertical-Velocity.h"

#include "LCS_AP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_LCS_AP_Horizontal_With_Vertical_Velocity_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_Horizontal_With_Vertical_Velocity, horizontal_Speed_And_Bearing),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Horizontal_Speed_And_Bearing,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"horizontal-Speed-And-Bearing"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_Horizontal_With_Vertical_Velocity, vertical_Velocity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Vertical_Velocity,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"vertical-Velocity"
		},
	{ ATF_POINTER, 1, offsetof(struct LCS_AP_Horizontal_With_Vertical_Velocity, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_ProtocolExtensionContainer_108P14,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_LCS_AP_Horizontal_With_Vertical_Velocity_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_Horizontal_With_Vertical_Velocity_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* horizontal-Speed-And-Bearing */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* vertical-Velocity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Horizontal_With_Vertical_Velocity_specs_1 = {
	sizeof(struct LCS_AP_Horizontal_With_Vertical_Velocity),
	offsetof(struct LCS_AP_Horizontal_With_Vertical_Velocity, _asn_ctx),
	asn_MAP_LCS_AP_Horizontal_With_Vertical_Velocity_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LCS_AP_Horizontal_With_Vertical_Velocity_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity = {
	"Horizontal-With-Vertical-Velocity",
	"Horizontal-With-Vertical-Velocity",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_tags_1,
	sizeof(asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_tags_1)
		/sizeof(asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_tags_1)
		/sizeof(asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_Horizontal_With_Vertical_Velocity_1,
	3,	/* Elements count */
	&asn_SPC_LCS_AP_Horizontal_With_Vertical_Velocity_specs_1	/* Additional specs */
};

