/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Velocity_Estimate_H_
#define	_LCS_AP_Velocity_Estimate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_Velocity_Estimate_PR {
	LCS_AP_Velocity_Estimate_PR_NOTHING,	/* No components present */
	LCS_AP_Velocity_Estimate_PR_horizontal_Velocity,
	LCS_AP_Velocity_Estimate_PR_horizontal_With_Vertical_Velocity,
	LCS_AP_Velocity_Estimate_PR_horizontal_Velocity_With_Uncertainty,
	LCS_AP_Velocity_Estimate_PR_horizontal_With_Vertical_Velocity_And_Uncertainty
	/* Extensions may appear below */
	
} LCS_AP_Velocity_Estimate_PR;

/* Forward declarations */
struct LCS_AP_Horizontal_Velocity;
struct LCS_AP_Horizontal_With_Vertical_Velocity;
struct LCS_AP_Horizontal_Velocity_With_Uncertainty;
struct LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty;

/* LCS_AP_Velocity-Estimate */
typedef struct LCS_AP_Velocity_Estimate {
	LCS_AP_Velocity_Estimate_PR present;
	union LCS_AP_Velocity_Estimate_u {
		struct LCS_AP_Horizontal_Velocity	*horizontal_Velocity;
		struct LCS_AP_Horizontal_With_Vertical_Velocity	*horizontal_With_Vertical_Velocity;
		struct LCS_AP_Horizontal_Velocity_With_Uncertainty	*horizontal_Velocity_With_Uncertainty;
		struct LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty	*horizontal_With_Vertical_Velocity_And_Uncertainty;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Velocity_Estimate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Velocity_Estimate;
extern asn_CHOICE_specifics_t asn_SPC_LCS_AP_Velocity_Estimate_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Velocity_Estimate_1[4];
extern asn_per_constraints_t asn_PER_type_LCS_AP_Velocity_Estimate_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Velocity_Estimate_H_ */
#include <asn_internal.h>
