/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Ellipsoid_Point_With_Altitude_H_
#define	_LCS_AP_Ellipsoid_Point_With_Altitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Geographical-Coordinates.h"
#include "LCS_AP_Altitude-And-Direction.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCS_AP_ProtocolExtensionContainer;

/* LCS_AP_Ellipsoid-Point-With-Altitude */
typedef struct LCS_AP_Ellipsoid_Point_With_Altitude {
	LCS_AP_Geographical_Coordinates_t	 geographical_Coordinates;
	LCS_AP_Altitude_And_Direction_t	 altitude_And_Direction;
	struct LCS_AP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ellipsoid_Point_With_Altitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ellipsoid_Point_With_Altitude;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ellipsoid_Point_With_Altitude_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ellipsoid_Point_With_Altitude_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Ellipsoid_Point_With_Altitude_H_ */
#include <asn_internal.h>
