/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_LCS-Client-Type.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_LCS_Client_Type_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  7 }	/* (0..7,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_LCS_AP_LCS_Client_Type_value2enum_1[] = {
	{ 0,	18,	"emergency-Services" },
	{ 1,	20,	"value-Added-Services" },
	{ 2,	22,	"pLMN-Operator-Services" },
	{ 3,	25,	"lawful-Intercept-Services" },
	{ 4,	32,	"pLMN-Operator-broadcast-Services" },
	{ 5,	16,	"pLMN-Operator-OM" },
	{ 6,	34,	"pLMN-Operator-Anonymous-Statistics" },
	{ 7,	39,	"pLMN-Operator-Target-MS-Service-Support" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_LCS_AP_LCS_Client_Type_enum2value_1[] = {
	0,	/* emergency-Services(0) */
	3,	/* lawful-Intercept-Services(3) */
	6,	/* pLMN-Operator-Anonymous-Statistics(6) */
	5,	/* pLMN-Operator-OM(5) */
	2,	/* pLMN-Operator-Services(2) */
	7,	/* pLMN-Operator-Target-MS-Service-Support(7) */
	4,	/* pLMN-Operator-broadcast-Services(4) */
	1	/* value-Added-Services(1) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_LCS_AP_LCS_Client_Type_specs_1 = {
	asn_MAP_LCS_AP_LCS_Client_Type_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_LCS_AP_LCS_Client_Type_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	9,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_LCS_Client_Type_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_LCS_Client_Type = {
	"LCS-Client-Type",
	"LCS-Client-Type",
	&asn_OP_NativeEnumerated,
	asn_DEF_LCS_AP_LCS_Client_Type_tags_1,
	sizeof(asn_DEF_LCS_AP_LCS_Client_Type_tags_1)
		/sizeof(asn_DEF_LCS_AP_LCS_Client_Type_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_LCS_Client_Type_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_LCS_Client_Type_tags_1)
		/sizeof(asn_DEF_LCS_AP_LCS_Client_Type_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_LCS_Client_Type_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_LCS_AP_LCS_Client_Type_specs_1	/* Additional specs */
};

