/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-CommonDataTypes"
 * 	found in "LCS-AP-CommonDataTypes.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_ProtocolExtensionID_H_
#define	_LCS_AP_ProtocolExtensionID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCS_AP_ProtocolExtensionID */
typedef long	 LCS_AP_ProtocolExtensionID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolExtensionID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolExtensionID;
asn_struct_free_f LCS_AP_ProtocolExtensionID_free;
asn_struct_print_f LCS_AP_ProtocolExtensionID_print;
asn_constr_check_f LCS_AP_ProtocolExtensionID_constraint;
per_type_decoder_f LCS_AP_ProtocolExtensionID_decode_aper;
per_type_encoder_f LCS_AP_ProtocolExtensionID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_ProtocolExtensionID_H_ */
#include <asn_internal.h>
