/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-CommonDataTypes"
 * 	found in "LCS-AP-CommonDataTypes.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_TriggeringMessage_H_
#define	_LCS_AP_TriggeringMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_TriggeringMessage {
	LCS_AP_TriggeringMessage_initiating_message	= 0,
	LCS_AP_TriggeringMessage_successful_outcome	= 1,
	LCS_AP_TriggeringMessage_unsuccessful_outcome	= 2,
	LCS_AP_TriggeringMessage_outcome	= 3
} e_LCS_AP_TriggeringMessage;

/* LCS_AP_TriggeringMessage */
typedef long	 LCS_AP_TriggeringMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_TriggeringMessage;
asn_struct_free_f LCS_AP_TriggeringMessage_free;
asn_struct_print_f LCS_AP_TriggeringMessage_print;
asn_constr_check_f LCS_AP_TriggeringMessage_constraint;
per_type_decoder_f LCS_AP_TriggeringMessage_decode_aper;
per_type_encoder_f LCS_AP_TriggeringMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_TriggeringMessage_H_ */
#include <asn_internal.h>
