/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_LCS_Cause_H_
#define	_LCS_AP_LCS_Cause_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Radio-Network-Layer-Cause.h"
#include "LCS_AP_Transport-Layer-Cause.h"
#include "LCS_AP_Protocol-Cause.h"
#include "LCS_AP_Misc-Cause.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_LCS_Cause_PR {
	LCS_AP_LCS_Cause_PR_NOTHING,	/* No components present */
	LCS_AP_LCS_Cause_PR_radio_Network_Layer,
	LCS_AP_LCS_Cause_PR_transport_Layer,
	LCS_AP_LCS_Cause_PR_protocol,
	LCS_AP_LCS_Cause_PR_misc
} LCS_AP_LCS_Cause_PR;

/* LCS_AP_LCS-Cause */
typedef struct LCS_AP_LCS_Cause {
	LCS_AP_LCS_Cause_PR present;
	union LCS_AP_LCS_Cause_u {
		LCS_AP_Radio_Network_Layer_Cause_t	 radio_Network_Layer;
		LCS_AP_Transport_Layer_Cause_t	 transport_Layer;
		LCS_AP_Protocol_Cause_t	 protocol;
		LCS_AP_Misc_Cause_t	 misc;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_LCS_Cause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_LCS_Cause;
extern asn_CHOICE_specifics_t asn_SPC_LCS_AP_LCS_Cause_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_LCS_Cause_1[4];
extern asn_per_constraints_t asn_PER_type_LCS_AP_LCS_Cause_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_LCS_Cause_H_ */
#include <asn_internal.h>
