/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-Containers"
 * 	found in "LCS-AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_ProtocolIE_Container_H_
#define	_LCS_AP_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCS_AP_Location_Request_IEs;
struct LCS_AP_Location_Response_IEs;
struct LCS_AP_Location_Abort_Request_IEs;
struct LCS_AP_Connection_Oriented_Information_IEs;
struct LCS_AP_Connectionless_Information_IEs;
struct LCS_AP_Reset_Request_IEs;
struct LCS_AP_Reset_Acknowledge_IEs;
struct LCS_AP_Ciphering_Key_Data_IEs;
struct LCS_AP_Ciphering_Key_Data_Result_IEs;

/* LCS_AP_ProtocolIE-Container */
typedef struct LCS_AP_ProtocolIE_Container_82P0 {
	A_SEQUENCE_OF(struct LCS_AP_Location_Request_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P0_t;
typedef struct LCS_AP_ProtocolIE_Container_82P1 {
	A_SEQUENCE_OF(struct LCS_AP_Location_Response_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P1_t;
typedef struct LCS_AP_ProtocolIE_Container_82P2 {
	A_SEQUENCE_OF(struct LCS_AP_Location_Abort_Request_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P2_t;
typedef struct LCS_AP_ProtocolIE_Container_82P3 {
	A_SEQUENCE_OF(struct LCS_AP_Connection_Oriented_Information_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P3_t;
typedef struct LCS_AP_ProtocolIE_Container_82P4 {
	A_SEQUENCE_OF(struct LCS_AP_Connectionless_Information_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P4_t;
typedef struct LCS_AP_ProtocolIE_Container_82P5 {
	A_SEQUENCE_OF(struct LCS_AP_Reset_Request_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P5_t;
typedef struct LCS_AP_ProtocolIE_Container_82P6 {
	A_SEQUENCE_OF(struct LCS_AP_Reset_Acknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P6_t;
typedef struct LCS_AP_ProtocolIE_Container_82P7 {
	A_SEQUENCE_OF(struct LCS_AP_Ciphering_Key_Data_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P7_t;
typedef struct LCS_AP_ProtocolIE_Container_82P8 {
	A_SEQUENCE_OF(struct LCS_AP_Ciphering_Key_Data_Result_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ProtocolIE_Container_82P8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P0;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P0_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P0_1[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P1;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P1_specs_3;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P1_3[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P2;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P2_specs_5;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P2_5[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P3;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P3_specs_7;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P3_7[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P4;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P4_specs_9;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P4_9[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P5;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P5_specs_11;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P5_11[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P6;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P6_specs_13;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P6_13[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P7;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P7_specs_15;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P7_15[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P8;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P8_specs_17;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P8_17[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P8_constr_17;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_ProtocolIE_Container_H_ */
#include <asn_internal.h>
