/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_UE-Positioning-Capability.h"

asn_TYPE_member_t asn_MBR_LCS_AP_UE_Positioning_Capability_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_UE_Positioning_Capability, lPP),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"lPP"
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_UE_Positioning_Capability_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_UE_Positioning_Capability_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* lPP */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_UE_Positioning_Capability_specs_1 = {
	sizeof(struct LCS_AP_UE_Positioning_Capability),
	offsetof(struct LCS_AP_UE_Positioning_Capability, _asn_ctx),
	asn_MAP_LCS_AP_UE_Positioning_Capability_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_UE_Positioning_Capability = {
	"UE-Positioning-Capability",
	"UE-Positioning-Capability",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_UE_Positioning_Capability_tags_1,
	sizeof(asn_DEF_LCS_AP_UE_Positioning_Capability_tags_1)
		/sizeof(asn_DEF_LCS_AP_UE_Positioning_Capability_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_UE_Positioning_Capability_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_UE_Positioning_Capability_tags_1)
		/sizeof(asn_DEF_LCS_AP_UE_Positioning_Capability_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_UE_Positioning_Capability_1,
	1,	/* Elements count */
	&asn_SPC_LCS_AP_UE_Positioning_Capability_specs_1	/* Additional specs */
};

