/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_H_
#define	_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_PR {
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_PR_NOTHING,	/* No components present */
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_PR_high_Accuracy_Uncertainty_Ellipse,
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_PR_high_Accuracy_Extended_Uncertainty_Ellipse
} LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_PR;

/* Forward declarations */
struct LCS_AP_High_Accuracy_Uncertainty_Ellipse;
struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse;

/* LCS_AP_High-Accuracy-Scalable-Uncertainty-Ellipse */
typedef struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse {
	LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_PR present;
	union LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_u {
		struct LCS_AP_High_Accuracy_Uncertainty_Ellipse	*high_Accuracy_Uncertainty_Ellipse;
		struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse	*high_Accuracy_Extended_Uncertainty_Ellipse;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse;
extern asn_CHOICE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_1[2];
extern asn_per_constraints_t asn_PER_type_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_H_ */
#include <asn_internal.h>
