/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-PDU-Contents"
 * 	found in "LCS-AP-PDU-Contents.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Connection_Oriented_Information_H_
#define	_LCS_AP_Connection_Oriented_Information_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCS_AP_ProtocolExtensionContainer;

/* LCS_AP_Connection-Oriented-Information */
typedef struct LCS_AP_Connection_Oriented_Information {
	LCS_AP_ProtocolIE_Container_82P3_t	 protocolIEs;
	struct LCS_AP_ProtocolExtensionContainer	*protocolExtensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Connection_Oriented_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Connection_Oriented_Information;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Connection_Oriented_Information_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Connection_Oriented_Information_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Connection_Oriented_Information_H_ */
#include <asn_internal.h>
