/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Ciphering_Data_Set_H_
#define	_LCS_AP_Ciphering_Data_Set_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Ciphering-Set-ID.h"
#include "LCS_AP_Ciphering-Key.h"
#include "LCS_AP_C0.h"
#include "LCS_AP_SIB-Types.h"
#include "LCS_AP_Validity-Start-Time.h"
#include "LCS_AP_Validity-Duration.h"
#include "LCS_AP_TAIs-List.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCS_AP_Ciphering-Data-Set */
typedef struct LCS_AP_Ciphering_Data_Set {
	LCS_AP_Ciphering_Set_ID_t	 ciphering_Set_ID;
	LCS_AP_Ciphering_Key_t	 ciphering_Key;
	LCS_AP_C0_t	 c0;
	LCS_AP_SIB_Types_t	 sib_Types;
	LCS_AP_Validity_Start_Time_t	 validity_Start_Time;
	LCS_AP_Validity_Duration_t	 validity_Duration;
	LCS_AP_TAIs_List_t	 tais_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ciphering_Data_Set_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ciphering_Data_Set;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ciphering_Data_Set_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ciphering_Data_Set_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Ciphering_Data_Set_H_ */
#include <asn_internal.h>
