/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-PDU-Descriptions"
 * 	found in "LCS-AP-PDU-Descriptions.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_LCS_AP_PDU_H_
#define	_LCS_AP_LCS_AP_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_LCS_AP_PDU_PR {
	LCS_AP_LCS_AP_PDU_PR_NOTHING,	/* No components present */
	LCS_AP_LCS_AP_PDU_PR_initiatingMessage,
	LCS_AP_LCS_AP_PDU_PR_successfulOutcome,
	LCS_AP_LCS_AP_PDU_PR_unsuccessfulOutcome
	/* Extensions may appear below */
	
} LCS_AP_LCS_AP_PDU_PR;

/* Forward declarations */
struct LCS_AP_InitiatingMessage;
struct LCS_AP_SuccessfulOutcome;
struct LCS_AP_UnsuccessfulOutcome;

/* LCS_AP_LCS-AP-PDU */
typedef struct LCS_AP_LCS_AP_PDU {
	LCS_AP_LCS_AP_PDU_PR present;
	union LCS_AP_LCS_AP_PDU_u {
		struct LCS_AP_InitiatingMessage	*initiatingMessage;
		struct LCS_AP_SuccessfulOutcome	*successfulOutcome;
		struct LCS_AP_UnsuccessfulOutcome	*unsuccessfulOutcome;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_LCS_AP_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_LCS_AP_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_LCS_AP_PDU_H_ */
#include <asn_internal.h>
