/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_LCS-QoS.h"

asn_TYPE_member_t asn_MBR_LCS_AP_LCS_QoS_1[] = {
	{ ATF_POINTER, 4, offsetof(struct LCS_AP_LCS_QoS, horizontal_Accuracy),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Horizontal_Accuracy,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"horizontal-Accuracy"
		},
	{ ATF_POINTER, 3, offsetof(struct LCS_AP_LCS_QoS, vertical_Requested),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Vertical_Requested,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"vertical-Requested"
		},
	{ ATF_POINTER, 2, offsetof(struct LCS_AP_LCS_QoS, vertical_Accuracy),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Vertical_Accuracy,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"vertical-Accuracy"
		},
	{ ATF_POINTER, 1, offsetof(struct LCS_AP_LCS_QoS, response_Time),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Response_Time,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"response-Time"
		},
};
static const int asn_MAP_LCS_AP_LCS_QoS_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_LCS_AP_LCS_QoS_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_LCS_QoS_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* horizontal-Accuracy */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* vertical-Requested */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* vertical-Accuracy */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* response-Time */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_LCS_QoS_specs_1 = {
	sizeof(struct LCS_AP_LCS_QoS),
	offsetof(struct LCS_AP_LCS_QoS, _asn_ctx),
	asn_MAP_LCS_AP_LCS_QoS_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_LCS_AP_LCS_QoS_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_LCS_QoS = {
	"LCS-QoS",
	"LCS-QoS",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_LCS_QoS_tags_1,
	sizeof(asn_DEF_LCS_AP_LCS_QoS_tags_1)
		/sizeof(asn_DEF_LCS_AP_LCS_QoS_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_LCS_QoS_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_LCS_QoS_tags_1)
		/sizeof(asn_DEF_LCS_AP_LCS_QoS_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_LCS_QoS_1,
	4,	/* Elements count */
	&asn_SPC_LCS_AP_LCS_QoS_specs_1	/* Additional specs */
};

