/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Altitude_And_Direction_H_
#define	_LCS_AP_Altitude_And_Direction_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Direction-Of-Altitude.h"
#include "LCS_AP_Altitude.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCS_AP_Altitude-And-Direction */
typedef struct LCS_AP_Altitude_And_Direction {
	LCS_AP_Direction_Of_Altitude_t	 direction_Of_Altitude;
	LCS_AP_Altitude_t	 altitude;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Altitude_And_Direction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Altitude_And_Direction;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Altitude_And_Direction_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Altitude_And_Direction_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Altitude_And_Direction_H_ */
#include <asn_internal.h>
