/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Ellipsoid_Arc_H_
#define	_LCS_AP_Ellipsoid_Arc_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Geographical-Coordinates.h"
#include "LCS_AP_Inner-Radius.h"
#include "LCS_AP_Uncertainty-Code.h"
#include "LCS_AP_Angle.h"
#include "LCS_AP_Confidence.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCS_AP_ProtocolExtensionContainer;

/* LCS_AP_Ellipsoid-Arc */
typedef struct LCS_AP_Ellipsoid_Arc {
	LCS_AP_Geographical_Coordinates_t	 geographical_Coordinates;
	LCS_AP_Inner_Radius_t	 inner_Radius;
	LCS_AP_Uncertainty_Code_t	 uncertainty_Radius;
	LCS_AP_Angle_t	 offset_Angle;
	LCS_AP_Angle_t	 included_Angle;
	LCS_AP_Confidence_t	 confidence;
	struct LCS_AP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ellipsoid_Arc_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ellipsoid_Arc;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ellipsoid_Arc_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ellipsoid_Arc_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Ellipsoid_Arc_H_ */
#include <asn_internal.h>
