/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-Containers"
 * 	found in "LCS-AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_ProtocolIE-Container.h"

#include "LCS_AP_ProtocolIE-Field.h"
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P4_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P5_constr_11 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P6_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P7_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_ProtocolIE_Container_82P8_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Request_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P0_specs_1 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P0),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P0 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P0_tags_1,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P0_tags_1)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P0_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P0_tags_1)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P0_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P0_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P0_1,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Response_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P1_specs_3 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P1),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P1 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P1_tags_3,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P1_tags_3)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P1_tags_3[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P1_tags_3)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P1_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P1_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P1_3,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Abort_Request_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P2_specs_5 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P2),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P2 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P2_tags_5,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P2_tags_5)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P2_tags_5[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P2_tags_5)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P2_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P2_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P2_5,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Connection_Oriented_Information_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P3_specs_7 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P3),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P3 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P3_tags_7,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P3_tags_7)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P3_tags_7[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P3_tags_7)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P3_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P3_constr_7,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P3_7,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P3_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P4_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Connectionless_Information_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P4_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P4_specs_9 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P4),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P4 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P4_tags_9,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P4_tags_9)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P4_tags_9[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P4_tags_9,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P4_tags_9)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P4_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P4_constr_9,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P4_9,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P4_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P5_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Reset_Request_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P5_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P5_specs_11 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P5),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P5 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P5_tags_11,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P5_tags_11)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P5_tags_11[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P5_tags_11,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P5_tags_11)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P5_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P5_constr_11,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P5_11,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P5_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P6_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Reset_Acknowledge_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P6_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P6_specs_13 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P6),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P6 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P6_tags_13,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P6_tags_13)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P6_tags_13[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P6_tags_13,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P6_tags_13)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P6_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P6_constr_13,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P6_13,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P6_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P7_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ciphering_Key_Data_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P7_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P7_specs_15 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P7),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P7 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P7_tags_15,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P7_tags_15)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P7_tags_15[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P7_tags_15,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P7_tags_15)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P7_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P7_constr_15,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P7_15,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P7_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_ProtocolIE_Container_82P8_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ciphering_Key_Data_Result_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_ProtocolIE_Container_82P8_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_LCS_AP_ProtocolIE_Container_82P8_specs_17 = {
	sizeof(struct LCS_AP_ProtocolIE_Container_82P8),
	offsetof(struct LCS_AP_ProtocolIE_Container_82P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_ProtocolIE_Container_82P8 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_LCS_AP_ProtocolIE_Container_82P8_tags_17,
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P8_tags_17)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P8_tags_17[0]), /* 1 */
	asn_DEF_LCS_AP_ProtocolIE_Container_82P8_tags_17,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P8_tags_17)
		/sizeof(asn_DEF_LCS_AP_ProtocolIE_Container_82P8_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_ProtocolIE_Container_82P8_constr_17,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_LCS_AP_ProtocolIE_Container_82P8_17,
	1,	/* Single element */
	&asn_SPC_LCS_AP_ProtocolIE_Container_82P8_specs_17	/* Additional specs */
};

