/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_High-Accuracy-Extended-Uncertainty-Ellipse.h"

#include "LCS_AP_ProtocolExtensionContainer.h"
static int
memb_LCS_AP_orientation_Major_Axis_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 179L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_LCS_AP_orientation_Major_Axis_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  179 }	/* (0..179) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse, high_Accuracy_Extended_Uncertainty_SemiMajor),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Code,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Extended-Uncertainty-SemiMajor"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse, high_Accuracy_Extended_Uncertainty_SemiMinor),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Code,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Extended-Uncertainty-SemiMinor"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse, orientation_Major_Axis),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_LCS_AP_orientation_Major_Axis_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_LCS_AP_orientation_Major_Axis_constraint_1
		},
		0, 0, /* No default value */
		"orientation-Major-Axis"
		},
	{ ATF_POINTER, 1, offsetof(struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_ProtocolExtensionContainer_108P12,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* high-Accuracy-Extended-Uncertainty-SemiMajor */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* high-Accuracy-Extended-Uncertainty-SemiMinor */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* orientation-Major-Axis */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_specs_1 = {
	sizeof(struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse),
	offsetof(struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse, _asn_ctx),
	asn_MAP_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse = {
	"High-Accuracy-Extended-Uncertainty-Ellipse",
	"High-Accuracy-Extended-Uncertainty-Ellipse",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tags_1,
	sizeof(asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tags_1)
		/sizeof(asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tags_1)
		/sizeof(asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_1,
	4,	/* Elements count */
	&asn_SPC_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_specs_1	/* Additional specs */
};

