/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Ciphering_Data_Ack_H_
#define	_LCS_AP_Ciphering_Data_Ack_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Ciphering-Set-ID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCS_AP_Ciphering-Data-Ack */
typedef struct LCS_AP_Ciphering_Data_Ack {
	A_SEQUENCE_OF(LCS_AP_Ciphering_Set_ID_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ciphering_Data_Ack_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ciphering_Data_Ack;
extern asn_SET_OF_specifics_t asn_SPC_LCS_AP_Ciphering_Data_Ack_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ciphering_Data_Ack_1[1];
extern asn_per_constraints_t asn_PER_type_LCS_AP_Ciphering_Data_Ack_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Ciphering_Data_Ack_H_ */
#include <asn_internal.h>
