/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-PDU-Descriptions"
 * 	found in "LCS-AP-PDU-Descriptions.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_InitiatingMessage.h"

static const long asn_VAL_1_LCS_AP_id_Location_Service_Request = 0;
static const long asn_VAL_1_LCS_AP_reject = 0;
static const long asn_VAL_2_LCS_AP_id_Connectionless_Information_Transfer = 2;
static const long asn_VAL_2_LCS_AP_reject = 0;
static const long asn_VAL_3_LCS_AP_id_Location_Abort = 3;
static const long asn_VAL_3_LCS_AP_reject = 0;
static const long asn_VAL_4_LCS_AP_id_Reset = 4;
static const long asn_VAL_4_LCS_AP_reject = 0;
static const long asn_VAL_5_LCS_AP_id_Ciphering_Key_Data_Delivery = 5;
static const long asn_VAL_5_LCS_AP_reject = 0;
static const long asn_VAL_6_LCS_AP_id_Connection_Oriented_Information_Transfer = 1;
static const long asn_VAL_6_LCS_AP_reject = 0;
static const asn_ioc_cell_t asn_IOS_LCS_AP_LCS_AP_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&InitiatingMessage", aioc__type, &asn_DEF_LCS_AP_Location_Request },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_LCS_AP_Location_Response },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_LCS_AP_Location_Response },
	{ "&procedureCode", aioc__value, &asn_DEF_LCS_AP_ProcedureCode, &asn_VAL_1_LCS_AP_id_Location_Service_Request },
	{ "&criticality", aioc__value, &asn_DEF_LCS_AP_Criticality, &asn_VAL_1_LCS_AP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_LCS_AP_Connectionless_Information },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_LCS_AP_ProcedureCode, &asn_VAL_2_LCS_AP_id_Connectionless_Information_Transfer },
	{ "&criticality", aioc__value, &asn_DEF_LCS_AP_Criticality, &asn_VAL_2_LCS_AP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_LCS_AP_Location_Abort_Request },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_LCS_AP_Location_Response },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_LCS_AP_ProcedureCode, &asn_VAL_3_LCS_AP_id_Location_Abort },
	{ "&criticality", aioc__value, &asn_DEF_LCS_AP_Criticality, &asn_VAL_3_LCS_AP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_LCS_AP_Reset_Request },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_LCS_AP_Reset_Acknowledge },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_LCS_AP_ProcedureCode, &asn_VAL_4_LCS_AP_id_Reset },
	{ "&criticality", aioc__value, &asn_DEF_LCS_AP_Criticality, &asn_VAL_4_LCS_AP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_LCS_AP_Ciphering_Key_Data },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_LCS_AP_Ciphering_Key_Data_Result },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_LCS_AP_Ciphering_Key_Data_Result },
	{ "&procedureCode", aioc__value, &asn_DEF_LCS_AP_ProcedureCode, &asn_VAL_5_LCS_AP_id_Ciphering_Key_Data_Delivery },
	{ "&criticality", aioc__value, &asn_DEF_LCS_AP_Criticality, &asn_VAL_5_LCS_AP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_LCS_AP_Connection_Oriented_Information },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_LCS_AP_ProcedureCode, &asn_VAL_6_LCS_AP_id_Connection_Oriented_Information_Transfer },
	{ "&criticality", aioc__value, &asn_DEF_LCS_AP_Criticality, &asn_VAL_6_LCS_AP_reject }
};
static const asn_ioc_set_t asn_IOS_LCS_AP_LCS_AP_ELEMENTARY_PROCEDURES_1[] = {
	{ 6, 5, asn_IOS_LCS_AP_LCS_AP_ELEMENTARY_PROCEDURES_1_rows }
};
static int
memb_LCS_AP_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_InitiatingMessage_LCS_AP_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_LCS_AP_LCS_AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct LCS_AP_InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_LCS_AP_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_InitiatingMessage_LCS_AP_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_LCS_AP_LCS_AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 0; /* &InitiatingMessage */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct LCS_AP_InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_LCS_AP_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_LCS_AP_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_LCS_AP_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_LCS_AP_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_LCS_AP_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage__value, choice.Location_Request),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Request,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Location-Request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage__value, choice.Connectionless_Information),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Connectionless_Information,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Connectionless-Information"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage__value, choice.Location_Abort_Request),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Location_Abort_Request,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Location-Abort-Request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage__value, choice.Reset_Request),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Reset_Request,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Reset-Request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage__value, choice.Ciphering_Key_Data),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Ciphering_Key_Data,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Ciphering-Key-Data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage__value, choice.Connection_Oriented_Information),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LCS_AP_Connection_Oriented_Information,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Connection-Oriented-Information"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 5 }, /* Location-Request */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 4 }, /* Connectionless-Information */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 3 }, /* Location-Abort-Request */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 2 }, /* Reset-Request */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 1 }, /* Ciphering-Key-Data */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 0 } /* Connection-Oriented-Information */
};
static asn_CHOICE_specifics_t asn_SPC_LCS_AP_value_specs_4 = {
	sizeof(struct LCS_AP_InitiatingMessage__value),
	offsetof(struct LCS_AP_InitiatingMessage__value, _asn_ctx),
	offsetof(struct LCS_AP_InitiatingMessage__value, present),
	sizeof(((struct LCS_AP_InitiatingMessage__value *)0)->present),
	asn_MAP_LCS_AP_value_tag2el_4,
	6,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_LCS_AP_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_LCS_AP_value_4,
	6,	/* Elements count */
	&asn_SPC_LCS_AP_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LCS_AP_InitiatingMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_ProcedureCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_LCS_AP_procedureCode_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_LCS_AP_procedureCode_constraint_1
		},
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Criticality,
		select_InitiatingMessage_LCS_AP_criticality_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_LCS_AP_criticality_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_LCS_AP_criticality_constraint_1
		},
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct LCS_AP_InitiatingMessage, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LCS_AP_value_4,
		select_InitiatingMessage_LCS_AP_value_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_LCS_AP_value_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_LCS_AP_value_constraint_1
		},
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_InitiatingMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_InitiatingMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_InitiatingMessage_specs_1 = {
	sizeof(struct LCS_AP_InitiatingMessage),
	offsetof(struct LCS_AP_InitiatingMessage, _asn_ctx),
	asn_MAP_LCS_AP_InitiatingMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_InitiatingMessage = {
	"InitiatingMessage",
	"InitiatingMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_InitiatingMessage_tags_1,
	sizeof(asn_DEF_LCS_AP_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_LCS_AP_InitiatingMessage_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_InitiatingMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_LCS_AP_InitiatingMessage_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_InitiatingMessage_1,
	3,	/* Elements count */
	&asn_SPC_LCS_AP_InitiatingMessage_specs_1	/* Additional specs */
};

