/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_Protocol-Cause.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_Protocol_Cause_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  6 }	/* (0..6,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_LCS_AP_Protocol_Cause_value2enum_1[] = {
	{ 0,	21,	"transfer-Syntax-Error" },
	{ 1,	28,	"abstract-Syntax-Error-Reject" },
	{ 2,	39,	"abstract-Syntax-Error-Ignore-And-Notify" },
	{ 3,	42,	"message-Not-Compatible-With-Receiver-State" },
	{ 4,	14,	"semantic-Error" },
	{ 5,	11,	"unspecified" },
	{ 6,	21,	"abstract-Syntax-Error" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_LCS_AP_Protocol_Cause_enum2value_1[] = {
	6,	/* abstract-Syntax-Error(6) */
	2,	/* abstract-Syntax-Error-Ignore-And-Notify(2) */
	1,	/* abstract-Syntax-Error-Reject(1) */
	3,	/* message-Not-Compatible-With-Receiver-State(3) */
	4,	/* semantic-Error(4) */
	0,	/* transfer-Syntax-Error(0) */
	5	/* unspecified(5) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_LCS_AP_Protocol_Cause_specs_1 = {
	asn_MAP_LCS_AP_Protocol_Cause_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_LCS_AP_Protocol_Cause_enum2value_1,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	8,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_Protocol_Cause_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_Protocol_Cause = {
	"Protocol-Cause",
	"Protocol-Cause",
	&asn_OP_NativeEnumerated,
	asn_DEF_LCS_AP_Protocol_Cause_tags_1,
	sizeof(asn_DEF_LCS_AP_Protocol_Cause_tags_1)
		/sizeof(asn_DEF_LCS_AP_Protocol_Cause_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_Protocol_Cause_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_Protocol_Cause_tags_1)
		/sizeof(asn_DEF_LCS_AP_Protocol_Cause_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_Protocol_Cause_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_LCS_AP_Protocol_Cause_specs_1	/* Additional specs */
};

