/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-Containers"
 * 	found in "LCS-AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_ProtocolExtensionField_H_
#define	_LCS_AP_ProtocolExtensionField_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_ProtocolExtensionID.h"
#include "LCS_AP_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "LCS_AP_Additional-PositioningDataSet.h"
#include "LCS_AP_Presence.h"
#include "LCS_AP_LCS-Service-Type-ID.h"
#include "LCS_AP_UE-Country-Determination-Indication.h"
#include "LCS_AP_E-CGI.h"
#include "LCS_AP_Cell-Portion-ID.h"
#include "LCS_AP_Civic-Address.h"
#include "LCS_AP_Barometric-Pressure.h"
#include "LCS_AP_UE-Area-Indication.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_E_CGI_ExtIEs__extensionValue_PR {
	LCS_AP_E_CGI_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_E_CGI_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR {
	LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs__extensionValue_PR {
	LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR {
	LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Ellipsoid_Arc_ExtIEs__extensionValue_PR {
	LCS_AP_Ellipsoid_Arc_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Ellipsoid_Arc_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Geographical_Coordinates_ExtIEs__extensionValue_PR {
	LCS_AP_Geographical_Coordinates_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Geographical_Coordinates_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR {
	LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs__extensionValue_PR {
	LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR {
	LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR {
	LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs__extensionValue_PR {
	LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs__extensionValue_PR {
	LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs__extensionValue_PR {
	LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Horizontal_Velocity_ExtIEs__extensionValue_PR {
	LCS_AP_Horizontal_Velocity_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Horizontal_Velocity_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs__extensionValue_PR {
	LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs__extensionValue_PR {
	LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs__extensionValue_PR {
	LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Point_ExtIEs__extensionValue_PR {
	LCS_AP_Point_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Point_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Point_With_Uncertainty_ExtIEs__extensionValue_PR {
	LCS_AP_Point_With_Uncertainty_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Point_With_Uncertainty_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Polygon_Point_ExtIEs__extensionValue_PR {
	LCS_AP_Polygon_Point_ExtIEs__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Polygon_Point_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Positioning_Data_ExtIEs__extensionValue_PR {
	LCS_AP_Positioning_Data_ExtIEs__extensionValue_PR_NOTHING,	/* No components present */
	LCS_AP_Positioning_Data_ExtIEs__extensionValue_PR_Additional_PositioningDataSet
} LCS_AP_Positioning_Data_ExtIEs__extensionValue_PR;
typedef enum LCS_AP_Location_Request_Extensions__extensionValue_PR {
	LCS_AP_Location_Request_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	LCS_AP_Location_Request_Extensions__extensionValue_PR_LCS_Service_Type_ID,
	LCS_AP_Location_Request_Extensions__extensionValue_PR_UE_Country_Determination_Indication
} LCS_AP_Location_Request_Extensions__extensionValue_PR;
typedef enum LCS_AP_Location_Response_Extensions__extensionValue_PR {
	LCS_AP_Location_Response_Extensions__extensionValue_PR_NOTHING,	/* No components present */
	LCS_AP_Location_Response_Extensions__extensionValue_PR_E_CGI,
	LCS_AP_Location_Response_Extensions__extensionValue_PR_Cell_Portion_ID,
	LCS_AP_Location_Response_Extensions__extensionValue_PR_Civic_Address,
	LCS_AP_Location_Response_Extensions__extensionValue_PR_Barometric_Pressure,
	LCS_AP_Location_Response_Extensions__extensionValue_PR_UE_Area_Indication
} LCS_AP_Location_Response_Extensions__extensionValue_PR;
typedef enum LCS_AP_Location_Abort_Request_Extensions__extensionValue_PR {
	LCS_AP_Location_Abort_Request_Extensions__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Location_Abort_Request_Extensions__extensionValue_PR;
typedef enum LCS_AP_Connection_Oriented_Information_Extensions__extensionValue_PR {
	LCS_AP_Connection_Oriented_Information_Extensions__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Connection_Oriented_Information_Extensions__extensionValue_PR;
typedef enum LCS_AP_Connectionless_Information_Extensions__extensionValue_PR {
	LCS_AP_Connectionless_Information_Extensions__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Connectionless_Information_Extensions__extensionValue_PR;
typedef enum LCS_AP_Reset_Request_Extensions__extensionValue_PR {
	LCS_AP_Reset_Request_Extensions__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Reset_Request_Extensions__extensionValue_PR;
typedef enum LCS_AP_Reset_Acknowledge_Extensions__extensionValue_PR {
	LCS_AP_Reset_Acknowledge_Extensions__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Reset_Acknowledge_Extensions__extensionValue_PR;
typedef enum LCS_AP_Ciphering_Key_Data_Extensions__extensionValue_PR {
	LCS_AP_Ciphering_Key_Data_Extensions__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Ciphering_Key_Data_Extensions__extensionValue_PR;
typedef enum LCS_AP_Ciphering_Key_Data_Result_Extensions__extensionValue_PR {
	LCS_AP_Ciphering_Key_Data_Result_Extensions__extensionValue_PR_NOTHING	/* No components present */
	
} LCS_AP_Ciphering_Key_Data_Result_Extensions__extensionValue_PR;

/* LCS_AP_ProtocolExtensionField */
typedef struct LCS_AP_E_CGI_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_E_CGI_ExtIEs__extensionValue {
		LCS_AP_E_CGI_ExtIEs__extensionValue_PR present;
		union LCS_AP_E_CGI_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_E_CGI_ExtIEs_t;
typedef struct LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue {
		LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR present;
		union LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs_t;
typedef struct LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs__extensionValue {
		LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs__extensionValue_PR present;
		union LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs_t;
typedef struct LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue {
		LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR present;
		union LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs_t;
typedef struct LCS_AP_Ellipsoid_Arc_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ellipsoid_Arc_ExtIEs__extensionValue {
		LCS_AP_Ellipsoid_Arc_ExtIEs__extensionValue_PR present;
		union LCS_AP_Ellipsoid_Arc_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ellipsoid_Arc_ExtIEs_t;
typedef struct LCS_AP_Geographical_Coordinates_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Geographical_Coordinates_ExtIEs__extensionValue {
		LCS_AP_Geographical_Coordinates_ExtIEs__extensionValue_PR present;
		union LCS_AP_Geographical_Coordinates_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Geographical_Coordinates_ExtIEs_t;
typedef struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue {
		LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__extensionValue_PR present;
		union LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs_t;
typedef struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs__extensionValue {
		LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs__extensionValue_PR present;
		union LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs_t;
typedef struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue {
		LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR present;
		union LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs_t;
typedef struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs__extensionValue {
		LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs__extensionValue_PR present;
		union LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs_t;
typedef struct LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs__extensionValue {
		LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs__extensionValue_PR present;
		union LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs_t;
typedef struct LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs__extensionValue {
		LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs__extensionValue_PR present;
		union LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs_t;
typedef struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs__extensionValue {
		LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs__extensionValue_PR present;
		union LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs_t;
typedef struct LCS_AP_Horizontal_Velocity_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Horizontal_Velocity_ExtIEs__extensionValue {
		LCS_AP_Horizontal_Velocity_ExtIEs__extensionValue_PR present;
		union LCS_AP_Horizontal_Velocity_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Horizontal_Velocity_ExtIEs_t;
typedef struct LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs__extensionValue {
		LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs__extensionValue_PR present;
		union LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs_t;
typedef struct LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs__extensionValue {
		LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs__extensionValue_PR present;
		union LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs_t;
typedef struct LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs__extensionValue {
		LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs__extensionValue_PR present;
		union LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs_t;
typedef struct LCS_AP_Point_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Point_ExtIEs__extensionValue {
		LCS_AP_Point_ExtIEs__extensionValue_PR present;
		union LCS_AP_Point_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Point_ExtIEs_t;
typedef struct LCS_AP_Point_With_Uncertainty_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Point_With_Uncertainty_ExtIEs__extensionValue {
		LCS_AP_Point_With_Uncertainty_ExtIEs__extensionValue_PR present;
		union LCS_AP_Point_With_Uncertainty_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Point_With_Uncertainty_ExtIEs_t;
typedef struct LCS_AP_Polygon_Point_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Polygon_Point_ExtIEs__extensionValue {
		LCS_AP_Polygon_Point_ExtIEs__extensionValue_PR present;
		union LCS_AP_Polygon_Point_ExtIEs__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Polygon_Point_ExtIEs_t;
typedef struct LCS_AP_Positioning_Data_ExtIEs {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Positioning_Data_ExtIEs__extensionValue {
		LCS_AP_Positioning_Data_ExtIEs__extensionValue_PR present;
		union LCS_AP_Positioning_Data_ExtIEs__LCS_AP_extensionValue_u {
			LCS_AP_Additional_PositioningDataSet_t	 Additional_PositioningDataSet;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Positioning_Data_ExtIEs_t;
typedef struct LCS_AP_Location_Request_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Location_Request_Extensions__extensionValue {
		LCS_AP_Location_Request_Extensions__extensionValue_PR present;
		union LCS_AP_Location_Request_Extensions__LCS_AP_extensionValue_u {
			LCS_AP_LCS_Service_Type_ID_t	 LCS_Service_Type_ID;
			LCS_AP_UE_Country_Determination_Indication_t	 UE_Country_Determination_Indication;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Location_Request_Extensions_t;
typedef struct LCS_AP_Location_Response_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Location_Response_Extensions__extensionValue {
		LCS_AP_Location_Response_Extensions__extensionValue_PR present;
		union LCS_AP_Location_Response_Extensions__LCS_AP_extensionValue_u {
			LCS_AP_E_CGI_t	 E_CGI;
			LCS_AP_Cell_Portion_ID_t	 Cell_Portion_ID;
			LCS_AP_Civic_Address_t	 Civic_Address;
			LCS_AP_Barometric_Pressure_t	 Barometric_Pressure;
			LCS_AP_UE_Area_Indication_t	 UE_Area_Indication;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Location_Response_Extensions_t;
typedef struct LCS_AP_Location_Abort_Request_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Location_Abort_Request_Extensions__extensionValue {
		LCS_AP_Location_Abort_Request_Extensions__extensionValue_PR present;
		union LCS_AP_Location_Abort_Request_Extensions__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Location_Abort_Request_Extensions_t;
typedef struct LCS_AP_Connection_Oriented_Information_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Connection_Oriented_Information_Extensions__extensionValue {
		LCS_AP_Connection_Oriented_Information_Extensions__extensionValue_PR present;
		union LCS_AP_Connection_Oriented_Information_Extensions__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Connection_Oriented_Information_Extensions_t;
typedef struct LCS_AP_Connectionless_Information_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Connectionless_Information_Extensions__extensionValue {
		LCS_AP_Connectionless_Information_Extensions__extensionValue_PR present;
		union LCS_AP_Connectionless_Information_Extensions__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Connectionless_Information_Extensions_t;
typedef struct LCS_AP_Reset_Request_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Reset_Request_Extensions__extensionValue {
		LCS_AP_Reset_Request_Extensions__extensionValue_PR present;
		union LCS_AP_Reset_Request_Extensions__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Reset_Request_Extensions_t;
typedef struct LCS_AP_Reset_Acknowledge_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Reset_Acknowledge_Extensions__extensionValue {
		LCS_AP_Reset_Acknowledge_Extensions__extensionValue_PR present;
		union LCS_AP_Reset_Acknowledge_Extensions__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Reset_Acknowledge_Extensions_t;
typedef struct LCS_AP_Ciphering_Key_Data_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ciphering_Key_Data_Extensions__extensionValue {
		LCS_AP_Ciphering_Key_Data_Extensions__extensionValue_PR present;
		union LCS_AP_Ciphering_Key_Data_Extensions__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ciphering_Key_Data_Extensions_t;
typedef struct LCS_AP_Ciphering_Key_Data_Result_Extensions {
	LCS_AP_ProtocolExtensionID_t	 id;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_Ciphering_Key_Data_Result_Extensions__extensionValue {
		LCS_AP_Ciphering_Key_Data_Result_Extensions__extensionValue_PR present;
		union LCS_AP_Ciphering_Key_Data_Result_Extensions__LCS_AP_extensionValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensionValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Ciphering_Key_Data_Result_Extensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_E_CGI_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_E_CGI_ExtIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_E_CGI_ExtIEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs_specs_5;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs_specs_9;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ellipsoid_Point_With_Altitude_ExtIEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs_specs_13;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs_13[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ellipsoid_Arc_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ellipsoid_Arc_ExtIEs_specs_17;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ellipsoid_Arc_ExtIEs_17[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Geographical_Coordinates_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Geographical_Coordinates_ExtIEs_specs_21;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Geographical_Coordinates_ExtIEs_21[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs_specs_25;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse_ExtIEs_25[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs_specs_29;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse_ExtIEs_29[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs_specs_33;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_ExtIEs_33[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs_specs_37;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid_ExtIEs_37[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs_specs_41;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Geographical_Coordinates_ExtIEs_41[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs_specs_45;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Uncertainty_Ellipse_ExtIEs_45[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs_specs_49;
extern asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse_ExtIEs_49[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Horizontal_Velocity_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Horizontal_Velocity_ExtIEs_specs_53;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Horizontal_Velocity_ExtIEs_53[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs_specs_57;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Horizontal_With_Vertical_Velocity_ExtIEs_57[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs_specs_61;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Horizontal_Velocity_With_Uncertainty_ExtIEs_61[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs_specs_65;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty_ExtIEs_65[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Point_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Point_ExtIEs_specs_69;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Point_ExtIEs_69[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Point_With_Uncertainty_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Point_With_Uncertainty_ExtIEs_specs_73;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Point_With_Uncertainty_ExtIEs_73[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Polygon_Point_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Polygon_Point_ExtIEs_specs_77;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Polygon_Point_ExtIEs_77[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Positioning_Data_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Positioning_Data_ExtIEs_specs_81;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Positioning_Data_ExtIEs_81[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Location_Request_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Location_Request_Extensions_specs_85;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Location_Request_Extensions_85[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Location_Response_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Location_Response_Extensions_specs_89;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Location_Response_Extensions_89[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Location_Abort_Request_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Location_Abort_Request_Extensions_specs_93;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Location_Abort_Request_Extensions_93[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Connection_Oriented_Information_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Connection_Oriented_Information_Extensions_specs_97;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Connection_Oriented_Information_Extensions_97[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Connectionless_Information_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Connectionless_Information_Extensions_specs_101;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Connectionless_Information_Extensions_101[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Reset_Request_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Reset_Request_Extensions_specs_105;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Reset_Request_Extensions_105[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Reset_Acknowledge_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Reset_Acknowledge_Extensions_specs_109;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Reset_Acknowledge_Extensions_109[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ciphering_Key_Data_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ciphering_Key_Data_Extensions_specs_113;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ciphering_Key_Data_Extensions_113[3];
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Ciphering_Key_Data_Result_Extensions;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Ciphering_Key_Data_Result_Extensions_specs_117;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Ciphering_Key_Data_Result_Extensions_117[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_ProtocolExtensionField_H_ */
#include <asn_internal.h>
