/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Geographical_Area_H_
#define	_LCS_AP_Geographical_Area_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_Geographical_Area_PR {
	LCS_AP_Geographical_Area_PR_NOTHING,	/* No components present */
	LCS_AP_Geographical_Area_PR_point,
	LCS_AP_Geographical_Area_PR_point_With_Uncertainty,
	LCS_AP_Geographical_Area_PR_ellipsoidPoint_With_Uncertainty_Ellipse,
	LCS_AP_Geographical_Area_PR_polygon,
	LCS_AP_Geographical_Area_PR_ellipsoid_Point_With_Altitude,
	LCS_AP_Geographical_Area_PR_ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid,
	LCS_AP_Geographical_Area_PR_ellipsoid_Arc,
	/* Extensions may appear below */
	LCS_AP_Geographical_Area_PR_high_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse,
	LCS_AP_Geographical_Area_PR_high_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid,
	LCS_AP_Geographical_Area_PR_high_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse,
	LCS_AP_Geographical_Area_PR_high_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid
} LCS_AP_Geographical_Area_PR;

/* Forward declarations */
struct LCS_AP_Point;
struct LCS_AP_Point_With_Uncertainty;
struct LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse;
struct LCS_AP_Polygon;
struct LCS_AP_Ellipsoid_Point_With_Altitude;
struct LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid;
struct LCS_AP_Ellipsoid_Arc;
struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse;
struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid;
struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse;
struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid;

/* LCS_AP_Geographical-Area */
typedef struct LCS_AP_Geographical_Area {
	LCS_AP_Geographical_Area_PR present;
	union LCS_AP_Geographical_Area_u {
		struct LCS_AP_Point	*point;
		struct LCS_AP_Point_With_Uncertainty	*point_With_Uncertainty;
		struct LCS_AP_Ellipsoid_Point_With_Uncertainty_Ellipse	*ellipsoidPoint_With_Uncertainty_Ellipse;
		struct LCS_AP_Polygon	*polygon;
		struct LCS_AP_Ellipsoid_Point_With_Altitude	*ellipsoid_Point_With_Altitude;
		struct LCS_AP_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid	*ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid;
		struct LCS_AP_Ellipsoid_Arc	*ellipsoid_Arc;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse	*high_Accuracy_Ellipsoid_Point_With_Uncertainty_Ellipse;
		struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid	*high_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid;
		struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse	*high_Accuracy_Ellipsoid_Point_With_Scalable_Uncertainty_Ellipse;
		struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid	*high_Accuracy_Ellipsoid_Point_With_Altitude_And_Scalable_Uncertainty_Ellipsoid;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Geographical_Area_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Geographical_Area;
extern asn_CHOICE_specifics_t asn_SPC_LCS_AP_Geographical_Area_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Geographical_Area_1[11];
extern asn_per_constraints_t asn_PER_type_LCS_AP_Geographical_Area_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Geographical_Area_H_ */
#include <asn_internal.h>
