/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-PDU-Descriptions"
 * 	found in "LCS-AP-PDU-Descriptions.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_InitiatingMessage_H_
#define	_LCS_AP_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_ProcedureCode.h"
#include "LCS_AP_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "LCS_AP_Location-Request.h"
#include "LCS_AP_Location-Response.h"
#include "LCS_AP_Connectionless-Information.h"
#include "LCS_AP_Location-Abort-Request.h"
#include "LCS_AP_Reset-Request.h"
#include "LCS_AP_Reset-Acknowledge.h"
#include "LCS_AP_Ciphering-Key-Data.h"
#include "LCS_AP_Ciphering-Key-Data-Result.h"
#include "LCS_AP_Connection-Oriented-Information.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_InitiatingMessage__value_PR {
	LCS_AP_InitiatingMessage__value_PR_NOTHING,	/* No components present */
	LCS_AP_InitiatingMessage__value_PR_Location_Request,
	LCS_AP_InitiatingMessage__value_PR_Connectionless_Information,
	LCS_AP_InitiatingMessage__value_PR_Location_Abort_Request,
	LCS_AP_InitiatingMessage__value_PR_Reset_Request,
	LCS_AP_InitiatingMessage__value_PR_Ciphering_Key_Data,
	LCS_AP_InitiatingMessage__value_PR_Connection_Oriented_Information
} LCS_AP_InitiatingMessage__value_PR;

/* LCS_AP_InitiatingMessage */
typedef struct LCS_AP_InitiatingMessage {
	LCS_AP_ProcedureCode_t	 procedureCode;
	LCS_AP_Criticality_t	 criticality;
	struct LCS_AP_InitiatingMessage__value {
		LCS_AP_InitiatingMessage__value_PR present;
		union LCS_AP_InitiatingMessage__LCS_AP_value_u {
			LCS_AP_Location_Request_t	 Location_Request;
			LCS_AP_Connectionless_Information_t	 Connectionless_Information;
			LCS_AP_Location_Abort_Request_t	 Location_Abort_Request;
			LCS_AP_Reset_Request_t	 Reset_Request;
			LCS_AP_Ciphering_Key_Data_t	 Ciphering_Key_Data;
			LCS_AP_Connection_Oriented_Information_t	 Connection_Oriented_Information;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_InitiatingMessage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_InitiatingMessage_H_ */
#include <asn_internal.h>
