/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Positioning_Data_H_
#define	_LCS_AP_Positioning_Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCS_AP_Positioning_Data_Set;
struct LCS_AP_GNSS_Positioning_Data_Set;
struct LCS_AP_ProtocolExtensionContainer;

/* LCS_AP_Positioning-Data */
typedef struct LCS_AP_Positioning_Data {
	struct LCS_AP_Positioning_Data_Set	*positioning_Data_Set;	/* OPTIONAL */
	struct LCS_AP_GNSS_Positioning_Data_Set	*gNSS_Positioning_Data_Set;	/* OPTIONAL */
	struct LCS_AP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_Positioning_Data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Positioning_Data;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Positioning_Data_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_Positioning_Data_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Positioning_Data_H_ */
#include <asn_internal.h>
