/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_Vertical-Velocity.h"

static int
memb_LCS_AP_vertical_Speed_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_LCS_AP_vertical_Speed_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_LCS_AP_Vertical_Velocity_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_Vertical_Velocity, vertical_Speed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_LCS_AP_vertical_Speed_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_LCS_AP_vertical_Speed_constraint_1
		},
		0, 0, /* No default value */
		"vertical-Speed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_Vertical_Velocity, vertical_Speed_Direction),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Vertical_Speed_Direction,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"vertical-Speed-Direction"
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_AP_Vertical_Velocity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_Vertical_Velocity_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vertical-Speed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* vertical-Speed-Direction */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_Vertical_Velocity_specs_1 = {
	sizeof(struct LCS_AP_Vertical_Velocity),
	offsetof(struct LCS_AP_Vertical_Velocity, _asn_ctx),
	asn_MAP_LCS_AP_Vertical_Velocity_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_Vertical_Velocity = {
	"Vertical-Velocity",
	"Vertical-Velocity",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_Vertical_Velocity_tags_1,
	sizeof(asn_DEF_LCS_AP_Vertical_Velocity_tags_1)
		/sizeof(asn_DEF_LCS_AP_Vertical_Velocity_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_Vertical_Velocity_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_Vertical_Velocity_tags_1)
		/sizeof(asn_DEF_LCS_AP_Vertical_Velocity_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_Vertical_Velocity_1,
	2,	/* Elements count */
	&asn_SPC_LCS_AP_Vertical_Velocity_specs_1	/* Additional specs */
};

