/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_High-Accuracy-Scalable-Uncertainty-Ellipse.h"

#include "LCS_AP_High-Accuracy-Uncertainty-Ellipse.h"
#include "LCS_AP_High-Accuracy-Extended-Uncertainty-Ellipse.h"
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_1[] = {
	{ ATF_POINTER, 0, offsetof(struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse, choice.high_Accuracy_Uncertainty_Ellipse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Uncertainty_Ellipse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Uncertainty-Ellipse"
		},
	{ ATF_POINTER, 0, offsetof(struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse, choice.high_Accuracy_Extended_Uncertainty_Ellipse),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Extended_Uncertainty_Ellipse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Extended-Uncertainty-Ellipse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* high-Accuracy-Uncertainty-Ellipse */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* high-Accuracy-Extended-Uncertainty-Ellipse */
};
asn_CHOICE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_specs_1 = {
	sizeof(struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse),
	offsetof(struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse, _asn_ctx),
	offsetof(struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse, present),
	sizeof(((struct LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse *)0)->present),
	asn_MAP_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse = {
	"High-Accuracy-Scalable-Uncertainty-Ellipse",
	"High-Accuracy-Scalable-Uncertainty-Ellipse",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_1,
	2,	/* Elements count */
	&asn_SPC_LCS_AP_High_Accuracy_Scalable_Uncertainty_Ellipse_specs_1	/* Additional specs */
};

