/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_High-Accuracy-Ellipsoid-Point-With-Altitude-And-Uncertainty-Ellipsoid.h"

#include "LCS_AP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, high_Accuracy_Geographical_Coordinates),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Geographical_Coordinates,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Geographical-Coordinates"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, high_Accuracy_Altitude),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Altitude,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, high_Accuracy_Uncertainty_Ellipse),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Uncertainty_Ellipse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Uncertainty-Ellipse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, confidence),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Confidence,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"confidence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, high_Accuracy_Uncertainty_Altitude),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_High_Accuracy_Uncertainty_Code,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"high-Accuracy-Uncertainty-Altitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, vertical_Confidence),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Confidence,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"vertical-Confidence"
		},
	{ ATF_POINTER, 1, offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_ProtocolExtensionContainer_108P8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_oms_1[] = { 6 };
static const ber_tlv_tag_t asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* high-Accuracy-Geographical-Coordinates */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* high-Accuracy-Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* high-Accuracy-Uncertainty-Ellipse */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* confidence */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* high-Accuracy-Uncertainty-Altitude */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* vertical-Confidence */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_specs_1 = {
	sizeof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid),
	offsetof(struct LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid, _asn_ctx),
	asn_MAP_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid = {
	"High-Accuracy-Ellipsoid-Point-With-Altitude-And-Uncertainty-Ellipsoid",
	"High-Accuracy-Ellipsoid-Point-With-Altitude-And-Uncertainty-Ellipsoid",
	&asn_OP_SEQUENCE,
	asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tags_1,
	sizeof(asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tags_1)
		/sizeof(asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tags_1[0]), /* 1 */
	asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tags_1)
		/sizeof(asn_DEF_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_1,
	7,	/* Elements count */
	&asn_SPC_LCS_AP_High_Accuracy_Ellipsoid_Point_With_Altitude_And_Uncertainty_Ellipsoid_specs_1	/* Additional specs */
};

