/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_Additional_PositioningMethodAndUsage_H_
#define	_LCS_AP_Additional_PositioningMethodAndUsage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCS_AP_Additional-PositioningMethodAndUsage */
typedef OCTET_STRING_t	 LCS_AP_Additional_PositioningMethodAndUsage_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LCS_AP_Additional_PositioningMethodAndUsage_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_Additional_PositioningMethodAndUsage;
asn_struct_free_f LCS_AP_Additional_PositioningMethodAndUsage_free;
asn_struct_print_f LCS_AP_Additional_PositioningMethodAndUsage_print;
asn_constr_check_f LCS_AP_Additional_PositioningMethodAndUsage_constraint;
per_type_decoder_f LCS_AP_Additional_PositioningMethodAndUsage_decode_aper;
per_type_encoder_f LCS_AP_Additional_PositioningMethodAndUsage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_Additional_PositioningMethodAndUsage_H_ */
#include <asn_internal.h>
