/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_LCS_QoS_H_
#define	_LCS_AP_LCS_QoS_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Horizontal-Accuracy.h"
#include "LCS_AP_Vertical-Requested.h"
#include "LCS_AP_Vertical-Accuracy.h"
#include "LCS_AP_Response-Time.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCS_AP_LCS-QoS */
typedef struct LCS_AP_LCS_QoS {
	LCS_AP_Horizontal_Accuracy_t	*horizontal_Accuracy;	/* OPTIONAL */
	LCS_AP_Vertical_Requested_t	*vertical_Requested;	/* OPTIONAL */
	LCS_AP_Vertical_Accuracy_t	*vertical_Accuracy;	/* OPTIONAL */
	LCS_AP_Response_Time_t	*response_Time;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_LCS_QoS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_LCS_QoS;
extern asn_SEQUENCE_specifics_t asn_SPC_LCS_AP_LCS_QoS_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_LCS_QoS_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_LCS_QoS_H_ */
#include <asn_internal.h>
