/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "LCS_AP_Velocity-Estimate.h"

#include "LCS_AP_Horizontal-Velocity.h"
#include "LCS_AP_Horizontal-With-Vertical-Velocity.h"
#include "LCS_AP_Horizontal-Velocity-With-Uncertainty.h"
#include "LCS_AP_Horizontal-With-Vertical-Velocity-And-Uncertainty.h"
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LCS_AP_Velocity_Estimate_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_LCS_AP_Velocity_Estimate_1[] = {
	{ ATF_POINTER, 0, offsetof(struct LCS_AP_Velocity_Estimate, choice.horizontal_Velocity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Horizontal_Velocity,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"horizontal-Velocity"
		},
	{ ATF_POINTER, 0, offsetof(struct LCS_AP_Velocity_Estimate, choice.horizontal_With_Vertical_Velocity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"horizontal-With-Vertical-Velocity"
		},
	{ ATF_POINTER, 0, offsetof(struct LCS_AP_Velocity_Estimate, choice.horizontal_Velocity_With_Uncertainty),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Horizontal_Velocity_With_Uncertainty,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"horizontal-Velocity-With-Uncertainty"
		},
	{ ATF_POINTER, 0, offsetof(struct LCS_AP_Velocity_Estimate, choice.horizontal_With_Vertical_Velocity_And_Uncertainty),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LCS_AP_Horizontal_With_Vertical_Velocity_And_Uncertainty,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"horizontal-With-Vertical-Velocity-And-Uncertainty"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_AP_Velocity_Estimate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* horizontal-Velocity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* horizontal-With-Vertical-Velocity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* horizontal-Velocity-With-Uncertainty */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* horizontal-With-Vertical-Velocity-And-Uncertainty */
};
asn_CHOICE_specifics_t asn_SPC_LCS_AP_Velocity_Estimate_specs_1 = {
	sizeof(struct LCS_AP_Velocity_Estimate),
	offsetof(struct LCS_AP_Velocity_Estimate, _asn_ctx),
	offsetof(struct LCS_AP_Velocity_Estimate, present),
	sizeof(((struct LCS_AP_Velocity_Estimate *)0)->present),
	asn_MAP_LCS_AP_Velocity_Estimate_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LCS_AP_Velocity_Estimate = {
	"Velocity-Estimate",
	"Velocity-Estimate",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LCS_AP_Velocity_Estimate_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_LCS_AP_Velocity_Estimate_1,
	4,	/* Elements count */
	&asn_SPC_LCS_AP_Velocity_Estimate_specs_1	/* Additional specs */
};

