/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LCS-AP-IEs"
 * 	found in "LCS-AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_LCS_AP_ENB_ID_H_
#define	_LCS_AP_ENB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LCS_AP_Macro-eNB-ID.h"
#include "LCS_AP_Home-eNB-ID.h"
#include "LCS_AP_Short-Macro-eNB-ID.h"
#include "LCS_AP_Long-Macro-eNB-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LCS_AP_ENB_ID_PR {
	LCS_AP_ENB_ID_PR_NOTHING,	/* No components present */
	LCS_AP_ENB_ID_PR_macro_eNB_ID,
	LCS_AP_ENB_ID_PR_home_eNB_ID,
	/* Extensions may appear below */
	LCS_AP_ENB_ID_PR_short_macro_eNB_ID,
	LCS_AP_ENB_ID_PR_long_macro_eNB_ID
} LCS_AP_ENB_ID_PR;

/* LCS_AP_ENB-ID */
typedef struct LCS_AP_ENB_ID {
	LCS_AP_ENB_ID_PR present;
	union LCS_AP_ENB_ID_u {
		LCS_AP_Macro_eNB_ID_t	 macro_eNB_ID;
		LCS_AP_Home_eNB_ID_t	 home_eNB_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		LCS_AP_Short_Macro_eNB_ID_t	 short_macro_eNB_ID;
		LCS_AP_Long_Macro_eNB_ID_t	 long_macro_eNB_ID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCS_AP_ENB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCS_AP_ENB_ID;
extern asn_CHOICE_specifics_t asn_SPC_LCS_AP_ENB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_LCS_AP_ENB_ID_1[4];
extern asn_per_constraints_t asn_PER_type_LCS_AP_ENB_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LCS_AP_ENB_ID_H_ */
#include <asn_internal.h>
