/*
 * Copyright (C) 2026 by the M-Time Simulation project
 *
 * This file is part of Open5GS (AckNCT/open5gs `mtime-lcs` fork).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <string.h>
#include <stdbool.h>

#include "mme-context.h"
#include "ogs-lcs-ap.h"

#include "lcs-ap-handler.h"
#include "lcs-ap-path.h"
#include "lcs-ap-build.h"
#include "mme-slg-path.h"

/* Spec-accurate LPP/LPPa request/response APDU templates (generated by
 * tools/gen_lpp_lppa_templates.py). The MME classifies an inbound LPP/LPPa
 * request by matching it against the *_REQ templates and answers with the paired
 * *_RESP — it terminates the LPP/LPPa itself instead of relaying to a RAN. */
#include "lpp_lppa_templates.h"

static bool lcs_ap_apdu_match(
        const uint8_t *apdu, size_t apdu_len,
        const uint8_t *tmpl, size_t tmpl_len)
{
    return apdu && apdu_len == tmpl_len && memcmp(apdu, tmpl, tmpl_len) == 0;
}

/*
 * The E-SMLC sent an LPP/LPPa request wrapped in Connection-Oriented-Information.
 * Play UE (LPP) / eNB (LPPa): match the request, then send the canned measurement
 * response back on the same association, echoing the Correlation-ID.
 */
static void lcs_ap_answer_measurement(
        mme_esmlc_t *esmlc, LCS_AP_Connection_Oriented_Information_t *conn)
{
    uint32_t correlation_id = 0;
    long payload_type = -1;
    const uint8_t *apdu = NULL;
    size_t apdu_len = 0;
    const uint8_t *resp = NULL;
    size_t resp_len = 0;
    long resp_pt = 0;
    ogs_pkbuf_t *pkbuf = NULL;
    int i;

    ogs_assert(conn);

    for (i = 0; i < conn->protocolIEs.list.count; i++) {
        LCS_AP_Connection_Oriented_Information_IEs_t *ie =
                conn->protocolIEs.list.array[i];
        if (!ie)
            continue;
        switch (ie->value.present) {
        case LCS_AP_Connection_Oriented_Information_IEs__value_PR_Correlation_ID: {
            LCS_AP_Correlation_ID_t *c = &ie->value.choice.Correlation_ID;
            if (c->buf && c->size >= 4)
                correlation_id = ((uint32_t)c->buf[0] << 24) |
                        ((uint32_t)c->buf[1] << 16) |
                        ((uint32_t)c->buf[2] << 8) | c->buf[3];
            break;
        }
        case LCS_AP_Connection_Oriented_Information_IEs__value_PR_Payload_Type:
            payload_type = ie->value.choice.Payload_Type;
            break;
        case LCS_AP_Connection_Oriented_Information_IEs__value_PR_APDU: {
            LCS_AP_APDU_t *a = &ie->value.choice.APDU;
            apdu = a->buf;
            apdu_len = a->size;
            break;
        }
        default:
            break;
        }
    }

    if (!apdu) {
        ogs_error("[LCS-AP] Connection-Oriented-Information without an APDU");
        return;
    }

    if (payload_type == LCS_AP_Payload_Type_lPPa) {
        if (lcs_ap_apdu_match(apdu, apdu_len, LPPA_ECID_REQ, LPPA_ECID_REQ_LEN)) {
            resp = LPPA_ECID_RESP;
            resp_len = LPPA_ECID_RESP_LEN;
            resp_pt = LCS_AP_Payload_Type_lPPa;
        }
    } else if (payload_type == LCS_AP_Payload_Type_lPP) {
        if (lcs_ap_apdu_match(apdu, apdu_len, LPP_ECID_REQ, LPP_ECID_REQ_LEN)) {
            resp = LPP_ECID_RESP;
            resp_len = LPP_ECID_RESP_LEN;
            resp_pt = LCS_AP_Payload_Type_lPP;
        } else if (lcs_ap_apdu_match(apdu, apdu_len,
                LPP_OTDOA_REQ, LPP_OTDOA_REQ_LEN)) {
            resp = LPP_OTDOA_RESP;
            resp_len = LPP_OTDOA_RESP_LEN;
            resp_pt = LCS_AP_Payload_Type_lPP;
        }
        /* LPP_AGNSS_REQ and anything unrecognised: no canned answer. */
    }

    if (!resp) {
        ogs_warn("[LCS-AP] No canned answer for payload_type=%ld apdu_len=%zu "
                "(A-GNSS/unknown); not answering", payload_type, apdu_len);
        return;
    }

    ogs_info("[LCS-AP] Answer %s measurement request corr[0x%08x] with canned "
            "response (%zuB)",
            resp_pt == LCS_AP_Payload_Type_lPPa ? "LPPa" : "LPP",
            correlation_id, resp_len);

    pkbuf = lcs_ap_build_connection_oriented_info(
            correlation_id, resp_pt, resp, resp_len);
    if (!pkbuf) {
        ogs_error("lcs_ap_build_connection_oriented_info() failed");
        return;
    }
    lcs_ap_send_to_esmlc(esmlc, pkbuf, esmlc->ostream_id);
}

/*
 * Decode and log an inbound SLs LCS-AP PDU from the E-SMLC. The expected
 * message in the positioning flow is the SuccessfulOutcome carrying a
 * Location-Service-Response. Deep IE extraction (the Location-Estimate) is
 * wired up with the positioning glue in increment 3c.
 */
void lcs_ap_handle_message(mme_esmlc_t *esmlc, ogs_pkbuf_t *pkbuf)
{
    int rv;
    ogs_lcs_ap_message_t message;

    ogs_assert(esmlc);
    ogs_assert(pkbuf);

    memset(&message, 0, sizeof(message));
    rv = ogs_lcs_ap_decode(&message, pkbuf);
    if (rv != OGS_OK) {
        ogs_error("[LCS-AP] Failed to decode message from E-SMLC");
        return;
    }

    switch (message.present) {
    case LCS_AP_LCS_AP_PDU_PR_initiatingMessage: {
        LCS_AP_InitiatingMessage_t *im = message.choice.initiatingMessage;
        if (im->procedureCode ==
                LCS_AP_id_Connection_Oriented_Information_Transfer &&
                im->value.present ==
                LCS_AP_InitiatingMessage__value_PR_Connection_Oriented_Information) {
            ogs_info("[LCS-AP] Rx Connection-Oriented-Information (LPP/LPPa) "
                    "from E-SMLC [%s]",
                    ogs_sockaddr_to_string_static(esmlc->sa_list));
            lcs_ap_answer_measurement(
                    esmlc, &im->value.choice.Connection_Oriented_Information);
        } else {
            ogs_info("[LCS-AP] Rx InitiatingMessage (procedureCode %d) "
                    "from E-SMLC [%s]",
                    (int)im->procedureCode,
                    ogs_sockaddr_to_string_static(esmlc->sa_list));
        }
        break;
    }
    case LCS_AP_LCS_AP_PDU_PR_successfulOutcome: {
        LCS_AP_SuccessfulOutcome_t *out = message.choice.successfulOutcome;
        uint32_t correlation_id = 0;
        uint8_t gad[7] = {0};
        int gad_len = 0;

        ogs_info("[LCS-AP] Rx Location-Service-Response (procedureCode %d) "
                "from E-SMLC [%s]",
                (int)out->procedureCode,
                ogs_sockaddr_to_string_static(esmlc->sa_list));

        if (out->value.present ==
                LCS_AP_SuccessfulOutcome__value_PR_Location_Response) {
            LCS_AP_Location_Response_t *resp =
                    &out->value.choice.Location_Response;
            int i;
            for (i = 0; i < resp->protocolIEs.list.count; i++) {
                LCS_AP_Location_Response_IEs_t *ie =
                        resp->protocolIEs.list.array[i];
                if (!ie)
                    continue;
                if (ie->id == LCS_AP_id_Correlation_ID && ie->value.present ==
                        LCS_AP_Location_Response_IEs__value_PR_Correlation_ID) {
                    LCS_AP_Correlation_ID_t *c =
                            &ie->value.choice.Correlation_ID;
                    if (c->buf && c->size >= 4)
                        correlation_id = ((uint32_t)c->buf[0] << 24) |
                                ((uint32_t)c->buf[1] << 16) |
                                ((uint32_t)c->buf[2] << 8) | c->buf[3];
                } else if (ie->id == LCS_AP_id_Location_Estimate &&
                        ie->value.present ==
                        LCS_AP_Location_Response_IEs__value_PR_Geographical_Area) {
                    LCS_AP_Geographical_Area_t *ga =
                            &ie->value.choice.Geographical_Area;
                    if (ga->present == LCS_AP_Geographical_Area_PR_point &&
                            ga->choice.point) {
                        LCS_AP_Geographical_Coordinates_t *gc =
                                &ga->choice.point->geographical_Coordinates;
                        /* Geographical-Coordinates -> GAD ellipsoid point: the
                         * 2^23 latitude / 2^24 longitude scaling is identical. */
                        uint32_t latv = (uint32_t)gc->degreesLatitude & 0x7FFFFF;
                        uint32_t lonv = (uint32_t)gc->degreesLongitude & 0xFFFFFF;
                        if (gc->latitudeSign != 0) /* south */
                            latv |= 0x800000;
                        gad[0] = 0x00; /* shape type 0 = Ellipsoid Point */
                        gad[1] = (latv >> 16) & 0xFF;
                        gad[2] = (latv >> 8) & 0xFF;
                        gad[3] = latv & 0xFF;
                        gad[4] = (lonv >> 16) & 0xFF;
                        gad[5] = (lonv >> 8) & 0xFF;
                        gad[6] = lonv & 0xFF;
                        gad_len = 7;
                    }
                }
            }
        }

        /* Hand the position to the parked SLg PLA (no-op for the self-test id). */
        mme_slg_answer_location(correlation_id, gad_len ? gad : NULL, gad_len);
        break;
    }
    case LCS_AP_LCS_AP_PDU_PR_unsuccessfulOutcome:
        ogs_warn("[LCS-AP] Rx UnsuccessfulOutcome (procedureCode %d) "
                "from E-SMLC [%s]",
                (int)message.choice.unsuccessfulOutcome->procedureCode,
                ogs_sockaddr_to_string_static(esmlc->sa_list));
        break;
    default:
        ogs_warn("[LCS-AP] Rx unknown PDU present %d", message.present);
        break;
    }

    ogs_lcs_ap_free(&message);
}
